### ISSUE TITLE
Tests T1

### ISSUE THREAD

**Issue by Geeermy** [IIC2333/foro-2019-1#1]
¡Hola a todos y a todas!

Esta será la _issue_ oficial para que puedan compartir sus propios _tests_ y resultados.

¡Aprovechen este espacio al máximo para abordar todo lo solicitado! :-)

**Comment by B-Dominguez** [comment]
> Para corroborar sus resultados, debe hacer uso de los mismos tests de prueba que serán compartidos

Hola, existen esos test en alguna parte actualmente?

**Comment by Geeermy** [comment]
@B-Dominguez Aquí: http://iic2333.ing.puc.cl/

**Comment by ManuelOchagavia** [comment]
Una pregunta, me pasa que en el out1 (np) y out2 (p, q=5) todos los turnaround time se pasan por un segundo con respecto a los de referencia (Con el out3 (p, q=3) no porque lo arreglaron al parecer). ¿Es muy importante que sea exactamente igual a los de referencia?¿O puede ser que simplemente sea un segundo que no contaron? Eso, muchas gracias.

**Comment by nivek0o0** [comment]
Hola Manuel, 
los 3 outputs fueron actualizados. Te sugiero descargarlos de nuevo.
Saludos!

**Comment by jorgeriesco** [comment]
**TEST PROPUESTO 1:**

Hola, este es un test chico pero que deberia cubrir varios casos criticos, a ver que les sale para comparar:

Parametros:
Preemtive
q = 3

INPUT:
GERMY 8 2 4 2 4 1 2 3 1 1
RICHI 6 4 3 2 5 1 1 1
CRISTIAN 7 1 3 4 1 2 3 1

OUTPUT MIO:
GERMY,4,1,17,2,10
RICHI,3,0,18,3,14
CRISTIAN,4,1,17,0,10

**Comment by Geeermy** [comment]
@jorgeriesco Pon los parámetros de tu ejemplo para que tus compañeros/as puedan replicar los resultados. :-)

**Comment by jorgeriesco** [comment]
**TEST PROPUESTO 2:**

PARAMETROS:
preemtive
q = 3

INPUT:
GERMY 6 4 1 1
RICHI 9 2 3 3 8 1 1 1
CRISTIAN 7 0 4 1 2 1 1 2 3 1
TOTO 10 1 4 3 1 1 3 1 6 5

OUTPUT MIO:
GERMY,1,0,6,5,5
RICHI,3,1,16,2,11
CRISTIAN,4,0,17,0,12
TOTO,5,2,23,0,13

**Comment by IchottMano** [comment]
@jorgeriesco Hola!
Ten cuidado con la medición de usos de CPU, ya que al ojo en tu primer Output aparece que Germy usa 7 veces la CPU, a pesar que germy solo tiene 5 ráfagas y ninguna será bloqueada puesto a que ninguna es mayor al quantum. Pasa algo similar en tu segundo output con los procesos Richi, Cristian y Toto
Saludos!

**Comment by jorgeriesco** [comment]
Gracias a tu aclaración me di cuenta de que estaba entendiendo mal lo del quantum. Ahora los tests no son tan buenos como creía jajaj, incluso los borraría.

**Comment by IchottMano** [comment]
@jorgeriesco No es necesario que borres los tests, quizas editar los resultados para que adviertan del error y dejalos para que la gente los pruebe y vean que resultado les da, lo cual son libres de postear aquí 😄

**Comment by dagalloso** [comment]
@jorgeriesco me dio tu mismo resultado! Quize meter mi propio proceso a tu test (siendo completamente autoreferente jeje) a ver que les da 👀

Input:
GERMY 6 4 1 1
RICHI 9 2 3 3 8 1 1 1
CRISTIAN 7 0 4 1 2 1 1 2 3 1
TOTO 10 1 4 3 1 1 3 1 6 5
DANIEL 12 3 5 1 2 4 2 3 2 3 2 5

Lo corri en modo preemtive con q = 4 y me arrojó este resultado

GERMY,1,0,33,32,32
RICHI,3,0,33,4,28
CRISTIAN,4,0,36,0,31
TOTO,5,1,33,0,23
DANIEL,6,2,30,1,14
