### ISSUE TITLE
Tamaño de archivos

### ISSUE THREAD

**Issue by lily416** [IIC2333/foro-2019-1#100]
Hola 😅 

Estaba probando leer la información de los Bloques índice y sucede que en archivos como `germy.txt` y `Program in C.mkv` me da el mismo número que en el diagrama que entregaron, pero en:
- `SSBS.mp3` me da 6404051, cuando debería ser 6403795
   ![image](https://user-images.githubusercontent.com/26393515/57973788-13680300-797c-11e9-8de1-83f4181187b8.png)

- `free.jpg` me da 0 cuando debería ser 182087
   ![image](https://user-images.githubusercontent.com/26393515/57973771-fc291580-797b-11e9-90f5-6ea9307358f3.png)

No se me ocurre si se debe a que:
- Estoy leyendo un bloque incorrecto, pero es la misma función que dieron en la ayudantía, por lo que debería estar buena. 😓 
- Estoy calculando mal el tamaño, pero parece funcionar con los otros archivos por lo que sería raro que funcione con unos y otros no. 😞 
- O la información del diagrama no calza con el disco, es lo que siento que es más probable porque el archivo `SSBS.mp3` sale que tiene 2 _hardlinks_ (y al hacer `cr_ls` se repite el archivo), pero en el diagrama eso no se muestra, así que puede que el diagrama esté desactualizado con respecto al disco. 🤔😅 

Gracias por su tiempo 🙇‍♀

**Comment by Geeermy** [comment]
¡Hola Daniela!

En la ayudantía se usan solo los 2 bytes menos significativos porque el nro. de bloque puede ser representado solo con esos. No obstante, el tamaño de archivo hace uso de los 4 bytes. ¿Será que no estás incluyendo los dos bytes más significativos en tu cálculo?

¡Me cuentas!

**Comment by lily416** [comment]
@Geeermy si incluyo los 2 bytes más significativos :c

**Comment by Geeermy** [comment]
Ya, al parecer es un error de nuestra parte.

Te confirmo cuando terminemos de verificar/arreglar el asunto. :) ¡Por ahora asume que lo que hiciste está bien!

**Comment by Geeermy** [comment]
¡Hola! 

Pequeñas actualizaciones:

1) Efectivamente teníamos un tema con los _hardlinks_, además que habían algunos punteros mal puestos (lo que podría explicar el tamaño de 0 bytes de free.txt). Ya lo resolvimos y prontamente subiremos un nuevo disco.

2) Con respecto a los tamaños, estos fueron algo inexactos con respecto a los archivos originales que subimos (por ej., en el diagrama pusimos los tamaños que nos salía en el S.O., pero se escribieron más/menos bytes en la práctica). En ese sentido, básense netamente en lo que salga en el bloque índice de los archivos.

¡Mucho éxito!

**Comment by Geeermy** [comment]
Listo todo. Sugiero que leas el correo completo :)

¡Que te vaya bien!
