### ISSUE TITLE
bloques indirectos

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2333/foro-2019-1#101]
Hola,

Tengo la duda si los bloques indirectos se van asociando al archivo de manera que se van necesitando o desde que el archivo es creado estos ya están asignados?

*Asumí que los primeros 500 bloques de datos ya están asignados de un principio, pero aprovecho de preguntarlo tmbn por si acaso. También asumo que cuando hay un bloque indirecto asignado, automáticamente sus 512 bloques de datos ya están asignados tmbn.

Gracias!

**Comment by Geeermy** [comment]
¡Hola!

Todo puntero (ya sea directo a los datos o de direccionamiento indirecto) se asignan según necesidad (dado el tamaño del archivo) y no todos de forma automática. Si ese fuera el caso, perderíamos muchos bloques de forma innecesaria al no hacer uso de ellos. Te pido encarecidamente que lo cambies porque si no vas a estar copando tu disco con pocos archivos (además, podrás corroborar que _simdiskfilled_ no lo hace).

¡Éxito!

**Comment by jorgeriesco** [comment]
perfecto, gracias!
