### ISSUE TITLE
¿Retorno cr_mkdir?

### ISSUE THREAD

**Issue by jmwielandt** [IIC2333/foro-2019-1#102]
Hola,

En el enunciado nos especifican el retorno para muchas funciones, pero no para `cr_mkdir`. O sea, dice que es un `int` pero no nos dice qué valores se retornan bajo qué situaciones. ¿Qué debemos retornar?

Me sorprende un poco que nadie lo haya preguntado hasta ahora 🤔 

Gracias.

**Comment by Geeermy** [comment]
¡Hola!

Eso quedó de versiones pasadas del proyecto. Antes, era un entero que te permitía identificar si la función se había ejecutado de forma correcta (por ejemplo, un 1) o si había habido un error (por ejemplo, 0). Dado que no les estamos exigiendo manejo de errores, puedes retornar siempre el mismo número si lo deseas, no es importante. No obstante, si deseas ser más riguroso y optar al bonus, puedes retornar distintos enteros según si la operación fue exitosa o si fue un error (pueden haber enteros distintos para errores distintos).

¡Espero que se entienda! Éxito. :)
