### ISSUE TITLE
Duda cr_rm

### ISSUE THREAD

**Issue by auirarrazaval** [IIC2333/foro-2019-1#103]
Hola! En el enunciado, sobre la función cr_rm dice:
![image](https://user-images.githubusercontent.com/31079536/57988817-92cf0280-7a60-11e9-84ea-9a962bf65bec.png)
Mi pregunta es, también se pueden eliminar directorios? Por que en el enunciado solo hace referencia a los archivos

Muchas Gracias

**Comment by Geeermy** [comment]
¡Hola!

Optamos por eliminar la función que permitía remover directorios dado que era "fácil de replicar" con `cr_rm`. El método que está ahí descrito solo está pensado para archivos, pero si quieres extenderlo a directorios, se puede considerar como "bonus". :) 

¡Éxito!

**Comment by auirarrazaval** [comment]
Gracias @Geeermy 

Tengo otra pregunta: al momento de borrar un archivo completamente de disco, los 2000 bytes que contienen punteros a bloques de datos están ordenados? (los que estan ocupados son los primeros?) o puede pasar que esten entremezclados los bytes "validos" con algunos "inválidos" (0 <= valor <= 4)?

**Comment by auirarrazaval** [comment]
Muchas Gracias @Geeermy!

**Comment by Geeermy** [comment]
Vi que borraste la otra pregunta que hiciste jeje... la pondré porque igual le puede servir a alguien:

> Al momento de borrar un archivo completamente de disco, los 2000 bytes que contienen punteros a bloques de datos están ordenados? (los que están ocupados son los primeros?) o puede pasar que estén entremezclados los bytes "válidos" con algunos "inválidos" (0 <= valor <= 4)?

Sí, la idea es que estén ordenados siempre y eso va a depender de la implementación de su `cr_write`. Nosotros esperaríamos, por ejemplo, para un archivo de 5KB que los tres primeros punteros sean válidos y el resto no.

¡Buen lunes!

**Comment by auirarrazaval** [comment]
Perdón por haberlo borrado, me respondí solo como 10 minutos despues de escribirlo jajaja

**Comment by Calomi** [comment]
hola! que retorna cr_rm? ya que lo ponen como "int"

**Comment by Geeermy** [comment]
@Calomi La respuesta es la misma que la del retorno de `cr_mkdir`, la que puedes ver en #102.

¡Éxito!
