### ISSUE TITLE
cr_open

### ISSUE THREAD

**Issue by jvlara** [IIC2333/foro-2019-1#106]
Hola,
Para el caso donde es 'r', ¿se asume que se pasara un *path* correcto?

**Comment by Geeermy** [comment]
¡Hola!

Puedes asumirlo. No obstante, el manejar el caso contrario (por ej. archivo inexistente, o bien un directorio) puede ser considerado bonus.

¡Éxito!

**Comment by chuma9615** [comment]
y cuando la funcion se ejecuta con 'w', ¿solo se pueden abrir archivos no existentes?

**Comment by Geeermy** [comment]
También lo pueden asumir. Si manejan el caso de archivos existentes (lo que supone sobreescritura de archivos y liberación de punteros o uso de otros nuevos), pueden llevarse un **bonus interesante**, dado que es un caso más complicado (no tanto si ya implementaron `cr_write`, pero tienen que tener varias consideraciones).

¡Éxito! :)

**Comment by Geeermy** [comment]
Nota: @chuma9615 sabía que lo había contestado antes. Mira #98, ahí profundizo más en ese caso.
