### ISSUE TITLE
cr_read tamaño de nbytes

### ISSUE THREAD

**Issue by jvlara** [IIC2333/foro-2019-1#107]
Hola nuevamente, 
¿El valor de nbytes se puede asumir que sera menor al tamaño de 1 bloque? ¿o hay que poder cargar más en el buffer?
Gracias.

**Comment by Geeermy** [comment]
¡Hola!

El valor de `nbytes` puede ser lo que sea. No pueden asumir que se usará únicamente para leer un bloque.  En #105 doy algunos ejemplos.

¡Éxito! :)
