### ISSUE TITLE
SSBS.mp3

### ISSUE THREAD

**Issue by auirarrazaval** [IIC2333/foro-2019-1#108]
Hola! 
En el disco nuevo, SSBS.mp3 me aparece dos veces en el directorio "/" con el mismo nombre, es posible eso? Porque implicaría que pueden haber dos archivos llamados igual en un directorio, aunque apunten a bloques separados, lo que estaría mal.

**Comment by IchottMano** [comment]
Hola!
Son hardlinks que apuntan al mismo archivo, un bonito easter egg (totalmente a propósito 😅) que no voy a quitar ya que ya hemos cambiado suficiente el disco jajaja.
Este es un caso especial, aparte de esto puedes asumir que no habrán dos archivos con el mismo nombre en una carpeta.
Saludos!
