### ISSUE TITLE
LOAD

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2333/foro-2019-1#109]
Hola,

No entiendo bien load. Por ejemplo si tengo el siguiente parametro orig:

orig = "/home/yo/desktop/carpeta1"

Lo que hace es que toma carpeta1 y la copia en el root del disco junto con todos los archivos y carpetas que tiene en su interior? O estoy entendiendo mal?

Gracias!

**Comment by Geeermy** [comment]
¡Hola!

Es justamente lo que indicas. :) Sugiero que partas probando con `orig` como ruta a un archivo y después lo extiendes a carpetas.

¡Éxito!

**Comment by jorgeriesco** [comment]
Ok, gracias!
