### ISSUE TITLE
No puedo subir carpeta a servidor

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2333/foro-2019-1#11]
Hola,

Al intentar subir la carpeta con este comando:
sudo scp -r Desktop/T1 jnriesco@iic2333.ing.puc.cl:/user/jnriesco/T1

me dice: 
"jnriesco is not in the sudoers file.  This incident will be reported."

Por lo que entiendo jnriesco ya no está. No se si lo subo simplemente a user o que debo hacer.
Gracias!

**Comment by IchottMano** [comment]
Hola!

Estas intentando subir la carpeta desde el servidor?

Recuerda que para poder subir algo al servidor, no puedes estar conectado a este, se debe hacer desde tu computador. Intenta correr el comando luego de salir del servidor.

El mensaje que te entrega se debe a que intentas correr el comando *scp* con permisos de *super user (sudo)*, lo cual no puedes hacer ya que no tienes los permisos, sin embargo tu carpeta debería estar intacta.

Saludos!

**Comment by Geeermy** [comment]
@jorgeriesco por favor, confirma si resolviste tu problema o no. 👀

**Comment by Geeermy** [comment]
**Asumiremos que lo resolviste, si vuelves a tener problemas nos avisas.**

**Comment by jorgeriesco** [comment]
Hola, disculpen la demora, no me había podido meter en esto en todo este tiempo. 

Tenían razón, funcionó lo que dijeron gracias!
