### ISSUE TITLE
para probar cr_rm 

### ISSUE THREAD

**Issue by acrojas2** [IIC2333/foro-2019-1#111]
hola:
¿será posible que suban un disco con un archivo? esto sería util para probar la función cr_rm, ya que la verificación de que se hicieron bien los cambios es más facil si hay solo un archivo en el disco y con las funciones que nos dieron a implementar, eso sería posible solo si es que se tiene cr_write implementado y funcionando perfectamente, para así cargar con un archivo el disco vacio. Entonces, en pos de paralelizar la implementación de ambas funciones creo que sería de gran ayuda si nos suben un disco con un solo archivo en el bloque de directorio. 
Saludos!

**Comment by IchottMano** [comment]
Hola!
Acabo de subir al servidor (a la misma carpeta que los otros discos) el disco "one_file_disk.bin", que sólo tiene un archivo.
Saludos!
