### ISSUE TITLE
entradas de bloques no ocupados

### ISSUE THREAD

**Issue by fprebolledo** [IIC2333/foro-2019-1#112]
Buenas!
las entradas de los bloques que no estan ocupadas no vienen invalidas por default?
gracias.

**Comment by IchottMano** [comment]
Hola!
Me podrías especificar a que te refieres con "entradas de los bloques"? A los punteros?
Espero tu respuesta.
Saludos!

**Comment by fprebolledo** [comment]
asigne a un bloque de directorio un bloque vacio segun bitmap, sin embargo cada fila (de 32 byte) no tiene el byte 0 como un 1 (entrada invalida).

**Comment by IchottMano** [comment]
@francisca1 Si te refieres a eso, no, no vienen inválidas por default. Tu debes cambiar los bytes.
Saludos!
