### ISSUE TITLE
Duda cr_close

### ISSUE THREAD

**Issue by gbordoni** [IIC2333/foro-2019-1#113]
Hola!
No me queda claro con que se refiere con "garantizar que el archivo se encuentre actualizado en disco". Es checkear que el tamaño, los hardlinks, etc. sean los correctos antes de cerrarlo?

Saludos

**Comment by Geeermy** [comment]
¡Hola!

Más que revisar eso... asegurar que cuando cierres el `crFILE`, el disco binario se encuentre actualizado. Esto era importante en el caso de los que tenían el disco siempre en memoria (totalmente no recomendado), pero si no es el caso no tienes que preocuparte. Solo encárgate de liberar la memoria del `crFILE`.

¡Éxito!
