### ISSUE TITLE
cr_unload

### ISSUE THREAD

**Issue by fprebolledo** [IIC2333/foro-2019-1#114]
Hola! cuando se dice que se debe copiarel archivo de origen(disco) a destino (path en mi pc), se espera que los copie en forma de bytes verdad?.
Finalmente si es un archivo, depués de copiarlo en mi pc (por ejemplo hola.jpg), debería ver algo en ello ? alguna imagen x ? para saber si está bien.
Gracias!

**Comment by Geeermy** [comment]
1) Sí, los escribes en modo `wb`. La extensión del archivo, como viene naturalmente en el nombre del mismo en disco, se debiese interpretar bien en tu computador. El primer ejercicio que hicimos en la última ayudantía es un buen ejemplo de esto (pesco los bytes de un archivo y los escribo en otro de forma binaria).

2) Sí, deberías poder leer los archivos de texto, ver imágenes, poder escuchar audios, ver gifs y ver videos. Si algo te sale corrupto, algo estás haciendo mal al momento de reconstruir el archivo.

¡Éxito!

**Comment by fprebolledo** [comment]
Gracias!, otra consulta, si estoy copiando un bloque de datos y este tiene información hasta la mitad, se copia entero o hasta donde tiene información?

**Comment by Geeermy** [comment]
Hasta donde tenga información (haciendo uso del tamaño en bytes del archivo y, quizás, de un contador de los bytes que has leido). Si los usas todos, quizás en los archivos de texto no influya tanto, pero en el resto probablemente te queden resultados corruptos. :eyes:
