### ISSUE TITLE
estructura de sistema de archivos

### ISSUE THREAD

**Issue by fprebolledo** [IIC2333/foro-2019-1#115]
Hola! una consulta con esto:
![imagen](https://user-images.githubusercontent.com/26394880/58189496-98a72c80-7c88-11e9-82a2-ab1a8a8f31de.png)
que quieren decir con eso? Solo que se tenga en cuenta la estructura de estos en el disco y se mantenga consistente? u otra cosa? gracias!

**Comment by Geeermy** [comment]
¡Hola!

Más que todo, que sepan manejar la estructura de esos tipo de bloque. Por ejemplo, si aplican bien `cr_ls`, se considera que tienen buena la representación de bloque de directorio. Otro ejemplo más directo: si pueden escribir archivos grandes (por ej. de 10 MB), entonces tienen bien: la representación de bloque índice, de direccionamiento indirecto y de datos (incluso _bitmap_, si hacen uso de este).

En resumen: son puntos "regalados" si implementan bien los métodos que hacen uso de esos bloques. :)

¡Éxito!
