### ISSUE TITLE
Duda bonus

### ISSUE THREAD

**Issue by jpjoublan** [IIC2333/foro-2019-1#116]
Hola, tengo una duda con la parte de la documentación del bonus, esta tiene qu estar en un archivo aparte o dentro del mismo código? Y necesita algún formato especial o queda a nuestro criterio?

**Comment by Geeermy** [comment]
¡Hola!

En un archivo separado, PDF está bien.

No necesita ningún formato en especial, pero se espera una descripción similar a las funciones de cr_API del enunciado, con la diferencia de que en la suya, además, se indican los retornos para ciertos casos (errores o mal uso de cada función, por ejemplo), si es que los programaron.

Obviamente, se espera que lo que está documentado se vea reflejado en la corrección presencial. Si dicen que se controla un uso incorrecto de rutas en los métodos y lo describen en su documentación, se espera que en la corrección muestren ejemplos de eso dentro de sus `main.c`.

¡Si sigues con dudas me cuentas!
