### ISSUE TITLE
Problema haciendo unload 

### ISSUE THREAD

**Issue by jvlara** [IIC2333/foro-2019-1#117]
Hola!,
Cuando intento hacer unload del SSBS.mp3 me suena bien hasta cierto punto y luego se rompe, ¿que podría ser?, leo los 500 punteros del bloque indice y luego los 10 primeros punteros indirectos con sus respectivos bloques de datos en orden.
Gracias.

**Comment by IchottMano** [comment]
Hola!
¿Estas leyendo 10 punteros indirectos? (ese archivo no tiene tantos punteros indirectos) ¿Cuanto tiempo dice que se demora la cancion?
Podrian ser varios problemas distintos, como leer muchos datos o muy pocos, recuerda que te debes guiar por el tamaño del archivo para saber cuantos bytes tienes que leer para obtener el archivo completo.
Saludos!

**Comment by jvlara** [comment]
No alcanza a leer los 10 antes de llenarse, quizás leí mal el peso, tengo el diskfilled nuevo y me sale que el peso es 6404051 bytes .
