### ISSUE TITLE
Extensión plazo proyecto

### ISSUE THREAD

**Issue by NachoCasta** [IIC2333/foro-2019-1#119]
Holaa,

Alguna posibilidad de que extiendan el plazo de entrega del proyecto?

Gracias!
༼ つ ◕_◕ ༽つ

**Comment by ajahr95** [comment]
+1

**Comment by Geeermy** [comment]
¡Hola!

Veo difícil que podamos dar más plazo. No obstante, quedo de confirmar dado que el equipo docente está durmiendo ya (y yo voy en camino). Para no ilusionarlos: dudo muchísimo que se pueda dar más plazo que entregar a las 23:59.

¡Ánimo que queda poco!

PD: No vale si todas las reacciones son del mismo grupo jaja.

**Comment by TomasFuentes** [comment]
+1

**Comment by nfbalbontin** [comment]
+ 3

**Comment by jnhasard** [comment]
^4

**Comment by Geeermy** [comment]
A la brevedad subiré un anuncio al respecto.

**Comment by Calomi** [comment]
hasta el sabado!, hay pruebas en lo q queda de semana D: !! 
#subiendosePorElChorro jaja

**Comment by Geeermy** [comment]
@Calomi 😅
