### ISSUE TITLE
Máximo de procesos

### ISSUE THREAD

**Issue by fdominguezclaro** [IIC2333/foro-2019-1#12]
Hola!

Existe un máximo de procesos que van a usar en los archivos de test? A ver si podemos dejar un lago fijo. De lo contrario la lista de procesos tendríamos que poder agrandarla dinámicamente.

Gracias!

**Comment by IchottMano** [comment]
Hola!

Tu programa debe ser capaz de recibir una **cantidad arbitraria** de procesos, por lo que no existe un largo fijo o máximo.

Saludos!
