### ISSUE TITLE
Duda cr_hardlink

### ISSUE THREAD

**Issue by HenryBlairG** [IIC2333/foro-2019-1#120]
Con respecto al parámetro dest, la idea sería incluirlo en el bloque de directorio con el índice del bloque de origen? no me queda claro que necesito hacer con el archivo de destino. 

Desde ya muchas gracias!! :smile:

**Comment by Geeermy** [comment]
¡Hola!

Es importante que veas bien la descripción: **`dest` es una ruta**. Sí, tendrá un puntero al mismo bloque índice, pero este podría estar en una nueva entrada del mismo bloque directorio en el que se ubica `orig`, o bien en otro definido por su ruta. Ojo con eso.

¡Éxito!
