### ISSUE TITLE
Nuevas fechas

### ISSUE THREAD

**Issue by acrojas2** [IIC2333/foro-2019-1#121]
Hola:
Escribo para preguntar algunas cosas administrativas:
1. Según el programa hay que hacer aproximadamente 14 actividades y vamos recién en la 5. Pensando en que practicamente queda 1 mes  para el fin de todos. ¿Se harán todas? ¿qué pasa con eso?
2. Respecto a las tareas, son dos, mismas preguntas que en 1 y ¿Cual será la calendarización de eso?
3. Proyecto de redes. Mismas preguntas que en 1 y 2.
Saludos!

**Comment by lukassr** [comment]
Hola!.

1. Se tiene pensado hacer todas. En el caso en que no se alcancen a hacer todas, se hará el ajuste correspondiente al promedio.
2. Las tareas están calendarizadas desde a comienzos de semestre. Sin embargo, debido a los plazos extendidos de las otras entregas, se recalendizarán. Apenas tengamos las nuevas fechas se actualizarán en la página del curso.
3. El proyecto se acaba de subir. Lo íbamos a subir el viernes pero quisimos darles tranquilidad durante el fin de semana 😊

Saludos!
