### ISSUE TITLE
Código ayudantía P2

### ISSUE THREAD

**Issue by cilopez** [IIC2333/foro-2019-1#122]
Hola hoy en la ayudantía mostraron un código que me parecía bastante útil para empezar el proyecto, ¿lo van a subir?.
Saludos.

**Comment by lukassr** [comment]
Hola!

Ya está arriba el código y el diagrama que vimos en la ayudantía en la página del curso. Perdón la demora!

Saludos 🙂

**Comment by cilopez** [comment]
Gracias!
