### ISSUE TITLE
Protocolo para decir que comienza el turno

### ISSUE THREAD

**Issue by jvlara** [IIC2333/foro-2019-1#126]
Hola,
al momento de empezar a desarrollar los turnos me encontré que luego de *who's first* y que el primer jugador haga su jugada no hay un mensaje del protocolo para decirle al segundo jugador que haga su jugada. ¿que se hace en este caso?.

**Comment by nivek0o0** [comment]
Hola, los paquetes no diferencian entre _primer_ o _segundo_ jugador. Esta diferencia la hace el servidor dependiendo de a quién le envía un paquete primero.

Respondiendo a tu pregunta, el paquete para decirle a un jugador que comenzó su turno es **BoardState**. Este paquete tiene una doble función, actualizar el tablero en el cliente y además pedirle que juegue.

**Comment by jvlara** [comment]
Ahh ya, graciaas.
