### ISSUE TITLE
Red para probar P2

### ISSUE THREAD

**Issue by fprebolledo** [IIC2333/foro-2019-1#127]
Hola! en la ayudantía se dijo que habrá una red para probar nuestra tarea de forma no local, esta lista esta? cual es la ip y puerto que debemos poner ?.
Y como me puedo conectar con otras tareas?, se refiere solamente a que una tarea corra el server y las otras los clientes o algo más ? Gracias.

**Comment by lukassr** [comment]
Hola!

Vamos a intentar instalarla mañana, junto con las instrucciones que necesitan para usarla. Sin embargo, no es estrictamente necesaria. Pueden ocupar el *hotspot* del celular para conectarse entre computadores. Así que si quieren probarla, lo que pueden hacer es conectarse los dos a la misma red *hotspot*.

> ¿Cómo saber qué IP usar?

Recordemos que una IP es, en palabras simples, la dirección de un computador. En este caso, el cliente querrá conectarse al servidor, por lo tanto, el cliente necesita saber la IP del servidor para poder conectarse. También necesita el puerto, pero basta con que sean los mismos en el cliente y servidor y listo. 

> ¿Quién le da la IP al servidor?

Usualmente es automático, es decir, la red da una IP al momento de conectarse el computador. El problema de eso es que, puede pasar que luego de un tiempo, les cambie la IP, haciendo que ustedes tengan que cambiar el código del cliente para actualizar el IP y poder conectarse al servidor.

> Entonces, ¿qué hago?

Les recomendamos setear una IP manual al servidor, es decir, ponerle una IP directamente por ustedes, y que sea la misma que ocupe el cliente para conectarse. Así, evitan que tengan que cambiar el IP si es que la red se las cambia (esto es en las configuraciones del computador del *Wi-Fi*). 

> En resumen:
- En el computador del servidor, se conectan a la red y configuran la red con IP manual.
- En el código del servidor, incializan el *socket* con la IP 0.0.0.0.
- En el código del cliente, inicializan la conexión con el servidor usando la IP manual que setearon.


Y con respecto a tu pregunta, sí, que el servidor sea un computador y los clientes otros.

Si tienes más dudas, se va a hacer en la ayudantía del viernes una sesión de ayuda para ver estos casos de conexión. Pero te recomiendo que avances con todo lo del protocolo y el juego antes.

Espero que se haya entendido.
Saludos!
