### ISSUE TITLE
Cómo ven el tablero los clientes

### ISSUE THREAD

**Issue by acrojas2** [IIC2333/foro-2019-1#128]
Hola!
Cómo ven el tablero los clientes? Si el jugador uno tiene las fichas negras y el 2 las blancas, el tablero debe lucir asi para el jugador 2? 
<img width="965" alt="Captura de pantalla 2019-06-04 a la(s) 22 32 55" src="https://user-images.githubusercontent.com/26121354/58927370-49e3a300-871c-11e9-84fd-f4a1dffcacaf.png">

De ser así, como las ve el jugador 1?
Saludos!

**Comment by nivek0o0** [comment]
Hola,
no hay un requerimiento sobre la forma de mostrar el tablero, pero para que sea cómodo jugar te aconsejo imprimirlo invertido para el jugador 2. La idea es que sea lo más realista a una partida real, donde cada jugador comienza con sus fichas en su lado más cercano del tablero, osea, abajo en la consola.

También te aconsejo buscar caracteres **Unicode** (y cómo imprimirlos) para representar de mejor manera las fichas redondas, tanto blancas como negras (hay uno que se llama _eye fish_).

**Comment by acrojas2** [comment]
@nivek0o0 Subiste los caracteres unicode para el tablero? Tengo los que se ven en la foto :grimacing:, me faltan los cuadrados blancos y negros, no los pude encontrar y tablero luce así de feo :expressionless: : 

![2019-06-08 18 07 28](https://user-images.githubusercontent.com/26121354/59152734-4c921100-8a18-11e9-8cf6-4f4cb038c43a.jpg)

Saludos!

**Comment by nivek0o0** [comment]
Hola @acrojas2 

Los caracteres Unicode que uso son:
```
      'n' -> '\u25A1'
      'b' -> '\u25A0'
      'o' -> '\u25C9'
      'O' -> '\u265B'
      'x' -> '\u25CE'
      'X' -> '\u2655'
```
