### ISSUE TITLE
Duda captura múltiple

### ISSUE THREAD

**Issue by valerojasm** [IIC2333/foro-2019-1#130]
Hola!

Tenemos la duda de si se puede hacer captura múltiple por distintas direcciones, como en "zig-zag". Acá pongo un ejemplo para la captura de dos fichas, nuestra duda va principalmente porque como solo recibimos la casilla de inicio y la casilla final, pueden existir distintos caminos para llegar a esa celda capturando en distintas direcciones cada vez (en un caso donde sean mas de dos fichas las intermediarias). No sé si se entiende jajaj

![Screen Shot 2019-06-05 at 19 37 43](https://user-images.githubusercontent.com/37253682/58997907-8ff83f80-87cc-11e9-84ad-1b87afbb5561.png)

Gracias!

**Comment by nivek0o0** [comment]
Hola!

Capturar en zig-zag es totalmente válido, incluso si no es un zig-zag perfecto. La única restricción es que la captura sea hacia adelante si se trata de un peón.

Si hay distintos caminos de captura entre la posición inicial y la posición final, el servidor debe tomar el más largo, tal como explico en la issue #129 

Saludos!

#### **EDIT: No es necesario que encuentren el camino más largo, basta con el primero válido!**
