### ISSUE TITLE
Funcionamiento chat vs Juego

### ISSUE THREAD

**Issue by ValentinaAlvarezG** [IIC2333/foro-2019-1#131]
Hola!
Creo que no me queda claro del enunciado como funciona el chat con respecto al juego. O en verdad con respecto a como el servidor espera que los clientes le manden información.

Por ejemplo estaría bien considerar que (una vez establecida la conexión y lo del nickname y todo eso) el servidor espera que el jugador1 (el primero que juega) le mande algo, ya sea una jugada o un mensaje y sólo cuando él haya mandado una jugada valida, va a  empezar a esperar a que el jugador2 le envíe algo (de nuevo, jugada o mensaje).

O lo del chat es como independiente del juego y si es el turno del jugador1 el Jugador2 le puede estar hablando?

Eso :c aiura pliis

**Comment by nivek0o0** [comment]
Hola,
la primera alternativa que mencionas es la correcta. Como jugador puedo enviar uno o varios mensajes solo en mi turno (que empieza cuando el servidor me manda un **BoardState**).  Luego puedo hacer un movimiento para que termine mi turno.

El objetivo de esta medida es simplificar el flujo de sus clientes y servidores.

**Comment by ValentinaAlvarezG** [comment]
Yaaa, bacan gracias!!! :D
