### ISSUE TITLE
Duda con el no uso de Threads y Select repecto alDisconnect 

### ISSUE THREAD

**Issue by Calomi** [IIC2333/foro-2019-1#133]
Hola!, como mencionaron en el #123 y #125, podemos manejar las requests de forma "progresiva", pero un disconnect puede pasar en cualquier momento, no?

O al final tenemos que dejar la opción de desconectarse del cliente como parte del menú cuando le toque nomás a ese jugador? (y que no se pueda desconectar mientras no es su turno?!)

Tenemos que manejar que el client/server se haya caído repentinamente o que alguien haya cliqueado la "X" del terminal cerrándolo? o podemos asumir que se van a portar bien con eso? jaja

**Comment by nivek0o0** [comment]
Hola @calomi,

> ¿podemos manejar las requests de forma "progresiva"?

Ojo, solo la primera parte (que corresponde a la conexión) puede ser progresiva. El flujo de un juego es lo contrario, el cliente debe estar preparado para recibir cualquier paquete y tomar una acción al respecto.

> ¿tenemos que dejar la opción de desconectarse del cliente como parte del menú cuando le toque nomás a ese jugador?

Sí, el jugador puede desconectarse a través del menú **solo** durante su turno.

>¿Tenemos que manejar que el client/server se haya caído repentinamente o que alguien haya cliqueado la "X" del terminal cerrándolo?

Manejar que alguno de los programas se caiga, no, pueden asumir que eso no pasará. 
Pero sí deben manejar que el programa sea finalizado cerrando la consola o presionando Ctrl+C. No es complejo, puedes buscar cómo capturar ese tipo de señales dentro del programa. :smile:

**Comment by Calomi** [comment]
gracias por la aclaración!
