### ISSUE TITLE
Scores

### ISSUE THREAD

**Issue by Pyralspite** [IIC2333/foro-2019-1#134]
Hola, las puntuaciones de los jugadores son por capturas realizadas dentro de una partida o por partidas ganadas desde que se conectaron al servidor?
Si es el primer caso, la captura de una ficha normal y de una dama valen lo mismo?

Gracias c:

**Comment by nivek0o0** [comment]
Hola,

no está explícito en el enunciado, pero para dejarlo lo más simple posible, que el puntaje corresponda a la cantidad de fichas capturadas desde que comenzó la partida actual. La dama también suma 1.

Saludos!
