### ISSUE TITLE
Test de Clientes otros grupos

### ISSUE THREAD

**Issue by LuisFros** [IIC2333/foro-2019-1#135]
Como podemos probar conectarnos a otros servidores y recibir clientes distintos?
Vamos a compartir binarios entre grupos? 
Que recomiendan hacer al respecto, ya que es un requisito segun el enunciado

**Comment by nivek0o0** [comment]
Hola,
les subiremos (hoy ojalá) un binario de cliente y servidor para que puedan testear contra otra solución del problema.

Por otro lado, les sugiero que traten de conectar sus clientes y servidor desde distintos computadores en una red LAN.
