### ISSUE TITLE
Payload inexistente

### ISSUE THREAD

**Issue by ajahr95** [IIC2333/foro-2019-1#136]
Hola, tengo la duda en protocolos que no se especifica el payload, como por ejemplo 6.Start Game, si es que debemos dar necesariamente un payload size 0 y no entregar un payload o podemos entregar un payload que sea un mensaje del tipo : "la partida comenzó correctamente". Esto lo pregunto también porque supongo que podría solo mandar el id = 6 y que el cliente interprete que si el package tiene id=6 entonces la partida se inicio correctamente(y el mismo lo podría imprimir eso en su consola) . Esto es un ejemplo, pero va para todos los protocolos sin payload especificado.

**Comment by nivek0o0** [comment]
Hola, 
para los paquetes que no tienen payload, lo correcto es enviar solo dos bytes, el ID y un 0, nada más ni nada menos. Esto debe ser así para que al receptor no le queden bytes en el buffer del socket y los lea en el próximo recv pensando que se trata de un nuevo ID.

Por lo tanto, no hay problema con que el cliente imprima un texto que dependa del ID.
