### ISSUE TITLE
Tablero en "client" de ejemplo

### ISSUE THREAD

**Issue by LuisFros** [IIC2333/foro-2019-1#138]
![image](https://user-images.githubusercontent.com/21247721/59154393-7d397100-8a3f-11e9-90b5-d31ec741feac.png)
Las filas del cliente no deberia estar al revez? Como en el enunciado:
![image](https://user-images.githubusercontent.com/21247721/59154399-904c4100-8a3f-11e9-88e3-d7d85c1c090f.png)

**Comment by LuisFros** [comment]
Es decir, 1 al 8 hacia abajo en la perspectiva de blancas

**Comment by nivek0o0** [comment]
Hola @LuisFros 

Acabo de solucionar esa discrepancia y de subir nuevos ejecutables!

**Comment by LuisFros** [comment]
Gracias!
