### ISSUE TITLE
Movimiento Damas

### ISSUE THREAD

**Issue by auirarrazaval** [IIC2333/foro-2019-1#140]
Hola!

Durante el backtracking, una dama podría eventualemente empezar y terminar en la misma posición si es que efectúa los siguientes movimientos: 
```
comer ficha diagonal derecha arriba
comer ficha diagonal izquierda arriba
comer ficha diagonal izquierda abajo
comer ficha diagonal derecha abajo
```
Pero como en el backtracking incluímos la posición inicial, en el juego no se podría hacer lo anterior (se revisa que no se haya pasado por una coordenada anteriormente). Dejamos esto como asumido? O hay un error en mi implementación?

**Comment by nivek0o0** [comment]
Hola,
puedes asumir que esa situación jamás ocurrirá, por lo tanto no hay necesidad de manejarlo.

**Comment by auirarrazaval** [comment]
Gracias! 
Tengo otra duda, si en una jugada en la mitad una ficha llega al otro laod del tablero, se transforma en dama, y de ahi puede seguir jugando? (retrocediendo)

**Comment by nivek0o0** [comment]
No puede seguir jugando. Convertirse en dama implica que termina la jugada
