### ISSUE TITLE
Problemas para conectar con server dado.

### ISSUE THREAD

**Issue by fprebolledo** [IIC2333/foro-2019-1#141]
Hola! estaba probando nuestra tarea con el server que nos mandaron, sin embargo luego que me pide el nickname, cuando envio la respuesta, su server me dice que recibe un paquete con id desconocido.
![image](https://user-images.githubusercontent.com/26394880/59163127-7efc4680-8aca-11e9-8654-f2b3edbda5c8.png)
Sin embargo si veo el log de mi cliente:
![image](https://user-images.githubusercontent.com/26394880/59163132-a18e5f80-8aca-11e9-9b65-cd39c9937b2b.png)
envió el paquete correcto.
Pensé que quizá era la manera en la que formaba el paquete ya que hice las funciones antes de que dijeran el standart la cual era esta:
![image](https://user-images.githubusercontent.com/26394880/59163141-d39fc180-8aca-11e9-8e66-f42a352d9b5a.png)
Lo cambie a esto:
![image](https://user-images.githubusercontent.com/26394880/59163147-e619fb00-8aca-11e9-92e8-c961e5f64d34.png)
Sin embargo el problema sigue.
Gracias!

**Comment by fprebolledo** [comment]
Lo mismo para el cliente, envio boardstate y se le pregunta al cliente si quiere jugar denuevo.

**Comment by nivek0o0** [comment]
Hola @francisca1, ¿podrías indicarme por correo cómo estás enviando y recibiendo por el socket? O bien indicarme el repositorio para revisarlo yo mismo.
