### ISSUE TITLE
Envío de imágenes (bonus)

### ISSUE THREAD

**Issue by ariel-m-s** [IIC2333/foro-2019-1#142]
Hola!

¿Qué interfaz se debiese implementar para el envío de imágenes desde el servidor hacia los clientes? ¿Debiese haber un menu disponible desde la terminal del servidor?

Ariel

**Comment by nivek0o0** [comment]
Hola!
Basta con que cuando termine la partida el servidor envíe automáticamente a uno o ambos clientes una imagen almacenada en algún lado. 

El objetivo es que logren enviar un paquete pesado en segmentos y reensamblarlo correctamente.

**Comment by lukassr** [comment]
O también puedes elegir que aparezca una opción en el menú, pero basta con que tengan implementada la funcionalidad. 

Todas estas decisiones de diseño debiesen estar escritas en el readme.

Saludos!

**Comment by ariel-m-s** [comment]
Gracias!!
