### ISSUE TITLE
Conexión entre más computadores

### ISSUE THREAD

**Issue by ValentinaAlvarezG** [IIC2333/foro-2019-1#143]
Hola!

Nuestra tarea está funcionando piola bien (creo) de manera local. Pero no entendemos bien como hacer para que esto funcione en dos computadores diferentes :c

**Comment by lukassr** [comment]
Hola!

Tu pregunta es un poco amplia, pero intentaré cubrirla lo mejor que pueda. Te recomiendo que leas #127 , ahí puse información de cómo hacer la conexión.

Imaginemos que tenemos dos computadores; uno, donde va a estar el servidor y otro donde van a estar los clientes. La idea es que los dos computadores estén conectados a la misma red y tengan apagado cualquier firewall o software que pueda bloquear la conexión. Además, recomendamos usar una red local, o a través de un *hotspot* de celular, para evitar redes más complejas con posibilidad de bloqueo de puertos.

Recomendamos que el servidor y el cliente tengan una IP estática. Puedes usar los siguientes valores, dentro de la configuración de redes del computador:
IP computador servidor:`192.168.0.10`
IP computador clientes:`192.168.0.11`
Máscara: `255.255.255.0`
Puerta de enlace: 192.168.0.1
DNS server como `8.8.8.8`

Luego, al servidor lo inicias normalmente con IP `0.0.0.0`. Por ejemplo: 
`./server -i 0.0.0.0 -p 8888 -l`

Y, para iniciar a los clientes, utilizas la IP configurada manualmente:
`./client -i 192.168.0.10 -p 8888 -l`

Si no logras hacer la conexión, es porque hay algún software o Firewall bloqueando el puerto, o la red que utilizas tiene un filtro que impide que se realice la conexión. De todas formas, si tu tarea se conecta correctamente a nivel local, no debería haber problemas con que se realice la conexión a través de la red. Nosotros tenemos considerado esto al momento de la corrección.

Saludos!
