### ISSUE TITLE
Compartir repo - no tenemos poder

### ISSUE THREAD

**Issue by jmwielandt** [IIC2333/foro-2019-1#145]
Hola, con mi grupo estamos usando el repo del P1 y no tenemos poder para compartirlo.

¿Qué hacemos?

Creo que @IchottMano tiene poder para hacerlo.

[link](https://github.com/IIC2333/proyecto-sistemas-operativos-2019-1-grupos-101).

**Comment by nivek0o0** [comment]
Hola, nosotros ya tenenos acceso a esos repos!
Rellenen el form de todas maneras!

**Comment by jmwielandt** [comment]
Hecho
Gracias! :D
