### ISSUE TITLE
Corrección Proyecto

### ISSUE THREAD

**Issue by ajahr95** [IIC2333/foro-2019-1#147]
Hola, pueden detallar cómo será el proceso de corrección del proyecto? ¿Será presencial, automática con sus ejecutables?

**Comment by lukassr** [comment]
Hola!

No será presencial. Comenzaremos probando la pauta con su entrega, y forzando ciertos escenarios para ver cómo se comporta. Si todos estos escenarios logran ser correctos, se asegurarán buena parte de la nota. Después revisaremos el comportamiento que tenga entre cliente y servidor de su misma entrega. Y por último, revisaremos que estén todos y bien implementados los paquetes. 

Los porcentajes de cada ítem están especificados en el enunciado.

Cualquier otra cosa nos preguntas.

Saludos!

**Comment by ajahr95** [comment]
Gracias
