### ISSUE TITLE
T3 - Dudas 

### ISSUE THREAD

**Issue by malopez16** [IIC2333/foro-2019-1#149]
Hola! Unas consultas con respecto a la T3 :)

1. Cada vez que dicen _Acceso_, se están refiriendo exáctamente a entrar a la página, ¿correcto?
2. En la parte A, pregunta 2, consultan en qué formato se transfieren los datos. Sin querer que entreguen ni dar una respuesta, no entiendo a qué nivel están consultando esto. (Hay distintas subdivisiones de los datos dependidendo del nivel).
3. En la Parte A, pregunta 7, a qué se refieren con un "caso"?
4. En la Parte C, se indica que se incluya a los miembros observados en la red. ¿Es necesario poner a todos? Son muchísimos.
¡Gracias!

**Comment by lukassr** [comment]
Hola!

> Cada vez que dicen Acceso, se están refiriendo exáctamente a entrar a la página, ¿correcto?

Sí, a cualquier link que se ingresó durante la actividad.

> En la parte A, pregunta 2, consultan en qué formato se transfieren los datos. Sin querer que entreguen ni dar una respuesta, no entiendo a qué nivel están consultando esto. (Hay distintas subdivisiones de los datos dependidendo del nivel).

En primera instancia sería qué tipo de protocolo se usó, qué tipo de paquete se envió y qué tipo de formato de los datos que se enviaron (texto, imagen, etc.). Cualquier otro tipo de información que esté presente en Wireshark y que ustedes consideren que hay que agregarlo, no hay problema en que lo hagan.

> En la Parte A, pregunta 7, a qué se refieren con un "caso"?

Se refiere a cada _acceso_, cada link que se ingresó durante la actividad.

> En la Parte C, se indica que se incluya a los miembros observados en la red. ¿Es necesario poner a todos? Son muchísimos.

La pregunta 1 se refiere a los miembros de la red a los que se le hizo _ping_. Y sí, en ese caso, son todas, las 10 IPs a las que se le hizo _ping_ en la actividad.

Saludos!

**Comment by ajahr95** [comment]
En la pregunta A 6)  con los bytes de retorno se refieren al payload o al lenght?
En la B 2) pueden aclarar cuales son los rangos de segmento TCP?

**Comment by dagalloso** [comment]
Colándome también para la parte de los accesos. Hay accesos que pueden tener más de un GET, ¿estos los tengo que tratar por separado? pregunto porque por ejemplo cada uno de estos GETs podría tener su propio código HTTP de respuesta, ¿me fijo solo en el primero? ¿estoy muy perdido 😅?
Saludos!

**Comment by fdominguezclaro** [comment]
> Colándome también para la parte de los accesos. Hay accesos que pueden tener más de un GET, ¿estos los tengo que tratar por separado? pregunto porque por ejemplo cada uno de estos GETs podría tener su propio código HTTP de respuesta, ¿me fijo solo en el primero? ¿estoy muy perdido 😅?
> Saludos!

Yo tengo esa misma duda!

**Comment by ariel-m-s** [comment]
Hola @lukassr!

Sobre la **c1**. ¿No es válido si los miembros fueron descubiertos de otra manera?

Ariel

**Comment by nivek0o0** [comment]
@ajahr95 
Los **bytes de retorno** (A6) significa cuántos bytes se recibieron en total por cada acceso. Por ejemplo, 5000 bytes o 13000 bytes. Por lo tanto deben sumar todos los paquetes recibidos en consecuencia de dicho acceso. 
Los **rangos de segmentos** (B2) significa qué rango de bytes se transmitió en cada segmento de un recurso. Por ejemplo, el segmento 1 transmitió desde el byte 0 al 485, el segmento 2 entre el byte 486 y el 990.

@dagalloso (A3) Tienes toda la razón en que cada acceso puede implicar múltiples solicitudes GET. Se espera que muestren la información agregada de los códigos de respuesta. Por ejemplo, _se recibieron cinco 200 OK y dos 500 Internal Server Error_

@ariel-m-s sí es válido descubrir a los miembros de la red de otras maneras. El comando ping es solo una herramienta que les sugerimos para dicho objetivo. Lo importante es que puedan entregar la información solicitada de cada uno (MAC, IP, Fabricante). Ojo, solo de aquellos que "descubrieron", no todos en la red.

**Comment by nfbalbontin** [comment]
Hola! Para el caso de los bytes, ¿los paquetes de _Internal Server Error_ los sumamos igual o no los consideramos? ¿Lo mismo con todos los _OK_ que se reciben? 
Gracias!

**Comment by JoseDaroch** [comment]
Otra duda respecto a la B2. Tengo paquetes con más de 90 segmentos, es necesario hacer un desglose de cada uno de ellos?

**Comment by nivek0o0** [comment]
@nfbalbontin sí, hay que sumar todos los bytes de todos los paquetes recibidos a causa de los accesos. Saber que se recibió un archivo, un codigo 200 o un código 500 corresponde a una interpretación posterior del contenido.

@JoseDaroch no, basta con que ejemplifiquen con el primero para demostrar que lo entendieron!

**Comment by felipecr00** [comment]
> @ajahr95
> Los **bytes de retorno** (A6) significa cuántos bytes se recibieron en total por cada acceso. Por ejemplo, 5000 bytes o 13000 bytes. Por lo tanto deben sumar todos los paquetes recibidos en consecuencia de dicho acceso.
> Los **rangos de segmentos** (B2) significa qué rango de bytes se transmitió en cada segmento de un recurso. Por ejemplo, el segmento 1 transmitió desde el byte 0 al 485, el segmento 2 entre el byte 486 y el 990.
> 
> @dagalloso (A3) Tienes toda la razón en que cada acceso puede implicar múltiples solicitudes GET. Se espera que muestren la información agregada de los códigos de respuesta. Por ejemplo, _se recibieron cinco 200 OK y dos 500 Internal Server Error_
> 
> @ariel-m-s sí es válido descubrir a los miembros de la red de otras maneras. El comando ping es solo una herramienta que les sugerimos para dicho objetivo. Lo importante es que puedan entregar la información solicitada de cada uno (MAC, IP, Fabricante). Ojo, solo de aquellos que "descubrieron", no todos en la red.

Una duda con esto, en la B1, lo que se pide es la cantidad de segmentos que se transmiten para los accesos del enunciado solamente?, o se deben incluir además los que se producen los GET una vez realizados?; por ejemplo, si analisas el response del acceso http://192.168.1.9:3000/ se deben contar los que te despliega ese response simplemente? o tambien los que producen los gets que suceden entre medio (y que llaman a un monton de CSS y JS y bla bla)???

Help pls

**Comment by nivek0o0** [comment]
@felipecr00 la **cantidad de segmentos** debe contar **todos** los GETs que se generan a causa de un acceso (CSS, JS, etc). Recuerda que 1 paquete es transmitido al menos en 1 segmento.
