### ISSUE TITLE
PID

### ISSUE THREAD

**Issue by fprebolledo** [IIC2333/foro-2019-1#15]
El PID es el orden de llegada a la cola o el orden de llegada desde el txt ? 
Gracias :D.

**Comment by Geeermy** [comment]
Orden de llegada a la cola. :-)

Muy importante para los desempates ese detalle, ojo. 👀

**Comment by nivek0o0** [comment]
Hola Francisca,
para esta tarea asumiremos que los PID se van asignando secuencialmente según el orden de creación de los procesos, es decir, de menor a mayor tiempo de llegada en el input, lo que es equivalente a su orden de ingreso por primera vez a la cola ready.

**Comment by FelipeApablaza** [comment]
La prioridad usando pid es equivalente a si tengo dos procesos con igual prioridad entonces elijo el que tenga mayor tiempo de inicio ¿?

**Comment by Geeermy** [comment]
@FelipeApablaza Sí, ya que de esa forma asignas el `PID`. Procesos de mayor `PID` habrán sido creados posteriormente (_i.e._ tienen un tiempo de inicio mayor).
