### ISSUE TITLE
Tipo de Paquete

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2333/foro-2019-1#150]
Hola, 

No entiendo bien a que se refieren exactamente con tipo de paquete. Se hace mención de esto en la A.2 y en la A.5 por lo que he visto hasta ahora.

**Comment by jpjoublan** [comment]
Hola! Tengo esta misma duda, y quería agregar que cuando nos preguntan por el tipo, en algunos accesos se intercambian más de un tipo de datos, como html y png por ejemplo, en esos casos que tenemos que poner en el formato?

**Comment by nivek0o0** [comment]
Hola!

@jorgeriesco En la A2 se menciona el **formato**, esto se refiere a la extensión de los archivos que se transfieren. En la A5, el **tipo de paquete** se refiere al protocolo que sigue dicho paquete. Cualquier otro tipo de información que esté presente en Wireshark y que ustedes consideren que hay que agregarlo, no hay problema en que lo hagan.

@jpjoublan un acceso corresponde a entrar a 1 URL, este acceso puede tener múltiples solicitudes GET, y cada solicitud GET puede involucrar múltiples paquetes dependiendo del tamaño del contenido. Se espera que hagan una tabla resumen para cada acceso donde se indique cuántos paquetes de cada tipo y cada formato se recibieron.
