### ISSUE TITLE
T3 - parte(c)| icmp en vez de arp

### ISSUE THREAD

**Issue by B-Dominguez** [IIC2333/foro-2019-1#151]
Hola, en la parte (c) dice "... filtre los resultados de acuerdo al protocolo ARP". Por el protocolo ARP hay una lista de cientos de direcciones, y para ver con las que había hecho ping, filtré por icmp en cambio, que también muestran la información pedida.
Había olvidado que decía lo de ARP, por lo que basé mis respuestas en los ICMP. Es esto válido también? O debo hacerlo de nuevo?
En el segundo caso, cuántas direcciones hay que incluir en la (c).1

**Comment by nivek0o0** [comment]
Hola, puedes ocupar el filtro que desees, mientras te sirva para obtener los datos solicitados (MAC, IP, Fabricante) de cada uno de los hosts a los cuales les hiciste ping.
