### ISSUE TITLE
T3 - GETs a /assets/

### ISSUE THREAD

**Issue by fdominguezclaro** [IIC2333/foro-2019-1#152]
Para analizar cada acceso, hay que incluir todos los GET a los `/assests/`? Son cosas propias de Rails (servidor), entonces no se si vale la pena incluirlos... Además que estos GETS se hacen más de una vez a lo largo de todos los accesos.

Gracias!

**Comment by nivek0o0** [comment]
Hola, se deben considerar todos los recursos que se recibieron desde el servidor, así que los assets también. Obviamente no es necesario que analicen uno por uno, sino que los muestren de forma agregada, como por ejemplo en las preguntas A7,A3 y A6: _se hicieron 10 gets a assets, de los cuales se recibieron 9 códigos de respueta 200 OK y los bytes transferidos fueron 10.000_
