### ISSUE TITLE
Promedio de Actividades Totales

### ISSUE THREAD

**Issue by ajahr95** [IIC2333/foro-2019-1#153]
Hola, me quedó la duda, las actividades finalmente llegarán hasta la AC09 o seguirán subiendo hasta la AC14? Y si fuera el primer caso, cómo se calcularía la nota de actividades en la parte de Redes?

**Comment by lukassr** [comment]
Hola!

Tal como lo dijo @cruz en clases, **sí se subirán hasta la AC14**. El cálculo de la nota se modificó al siguiente criterio:

Promedio actividades Sistemas Operativos: AC1 hasta AC7, se cuentan las **5 mejores**.
Promedio actividades Redes: AC8 hasta AC14, se cuentan las **3 mejores**.

Saludos!
