### ISSUE TITLE
Materia exámen

### ISSUE THREAD

**Issue by Vanana** [IIC2333/foro-2019-1#154]
Desde dónde y hasta dónde es la materia para el examen?  :)

**Comment by lukassr** [comment]
Hola!

Tal como se dijo en clases, para el examen entra únicamente la materia de redes. Habrá una pregunta optativa de la materia de Sistemas Operativos, que de ser respondida, reemplazará la peor nota de las preguntas del Midterm (independientemente de la nota que se saquen).

Saludos!
