### ISSUE TITLE
Plazo T4

### ISSUE THREAD

**Issue by malopez16** [IIC2333/foro-2019-1#155]
Hola!

Recién noté que hay sólo una semana para hacer la T4. 
Más que por que es poco plazo, considerando que tendremos examenes y que las notas pueden cerrarse hasta el 9 de Julio, ¿Podríamos tener más plazo? 

Gracias,
Saludos :)

**Comment by acrojas2** [comment]
Hola!
Apoyo la petición, y también me gustaría decir que no solo este curso tiene actividades diferentes a pruebas escritas en periódo de exámenes. Creo que es un problema a nivel de escuela que permitan hacer actividades en este periodo donde es sabido que el examen de un curso en la mayoría de los casos engloba la materia de todo el curso, en otras ocasiones son reprobatorios, etc. Además de eso, a muchos de nostros nos pasa que tenemos los exámenes concentrados en un par de días entre esas semanas, por lo cual tener actividades extra a las cuales atender dificulta mucho el estudio para los exámenes.
Eso, saludos!

**Comment by lukassr** [comment]
Hola!

Acabo de mandar un aviso con el nuevo plazo de la T4.

Saludos.
