### ISSUE TITLE
Notas 

### ISSUE THREAD

**Issue by fprebolledo** [IIC2333/foro-2019-1#156]
Hola!, una consulta, aproximadamente cuando estarán las notas del proyecto de redes y la T3.
Gracias!

**Comment by lukassr** [comment]
Hola!

Estamos trabajando en eso para tenerlas lo antes posible. Lo más probable es que estén cercano al fin de semana.

Saludos.

**Comment by ajahr95** [comment]
Tendrán alguna nota antes del examen ?
