### ISSUE TITLE
AC12

### ISSUE THREAD

**Issue by diflores** [IIC2333/foro-2019-1#157]
¡Hola!

Me puse a revisar las últimas actividades que fueron subidas a EDX y noté que la AC12 tiene _deadline_ para mañana a las 14:00, ¿es eso correcto? Pregunto porque parece ser la última y es la única que no tiene fecha límite 8 de julio, lo que me pareció raro.

¡Saludos y gracias de antemano!

**Comment by lukassr** [comment]
Hola!

Sí, estaba mal, gracias por avisarnos. Ya lo corregimos 😊 

Saludos!
