### ISSUE TITLE
[AC11] Subredes IP - Subredes IP(i)-(ii)-(iii)-(iv)

### ISSUE THREAD

**Issue by malopez16** [IIC2333/foro-2019-1#158]
Hola!

Para la pregunta indicada en el título, nos consultan

> ¿Cuál es el nombre de la subred?

Pero no logro entender a qué se están refiriendo, más que nada por las palabras seleccionadas. ¿Las subredes tienen nombres? ¿Son calculables?

Gracias!
Saludos,
Mauricio.

**Comment by cruz** [comment]
Hola Mauricio,
El _nombre de la subred_ también es una dirección en formato IP. Se refiere a lo que se obtiene al aplicar el AND bit-a-bit (_bitwise AND_) entre una dirección IP y la máscara de subred. Dicho de otra forma, es la dirección que se obtiene dejando en 0 todos los bit que usan para identificar al _host_.

Por ejemplo, si tengo la IP `37.45.29.87`, y le aplico la máscara de 24 bit (`255.255.255.0`), obtengo `37.45.29.0`. Esta última dirección corresponde al _nombre de la subred_. Se dice que `37.45.29.87` pertenece a la subred `37.45.29.0`, o bien `37.45.29.0/24`.

Esta es la operación que usan los _host_ para determinar si un destinatario se encuentra en la misma red que el emisor del mensaje o no.

La página 340 del material adicional (voy a linkearlo desde EdX también) explica esto mismo.

**Comment by malopez16** [comment]
Excelente!
Me quedó clarísimo. Muchas gracias!

**Comment by LuisFros** [comment]
Hola!
En la misma pregunta de Subredes, creo que hay respuestas incorrectas. 

Por ejemplo, la pregunta (ii) "¿Cuál es la mayor IP que se puede asignar en esta red?" y "¿Cuál es la dirección de broadcast de esta red?"
Los mismo con la pregunta (iii) "¿Cuál es la dirección de broadcast de esta red?"
(Hay otras preguntas que tambien estan incorrectas )

He confirmado con fuentes externas y los valores que encontre deberian estar correctos. 

No puedo poner los resultados aca por razones obvias, pero me gustaria saber si efectivamente estan incorrectos.
Fuente: [Link](http://jodies.de/ipcalc)
Gracias
