### ISSUE TITLE
host maximos

### ISSUE THREAD

**Issue by fprebolledo** [IIC2333/foro-2019-1#159]
Hola, en el ejemplo de clases, dice que el maximo numero de host es 254, no entiendo porque se le restan 2, es por la dirección reservada al broadcast y dirección base?
![imagen](https://user-images.githubusercontent.com/26394880/60050326-5cf3ee00-969e-11e9-9bff-50ec44c17f04.png)
 Gracias!

**Comment by LuisFros** [comment]
Hola! (Soy estudiante tambien)
Tengo entendido que esa es la razon.
Se reservan 2 hosts, uno para el **nombre de la red** y otro para la **direccion de broadcast**
Esto significa que el rango de hosts disponibles para este ejemplo es 146.155.13.1 hasta 146.155.13.254

**Comment by fprebolledo** [comment]
Muchas gracias!

**Comment by cruz** [comment]
Gracias @LuisFros. Ésa es la respuesta. Esas dos IP no pueden usarse para un _host_ de la subred.
