### ISSUE TITLE
tamaño subred

### ISSUE THREAD

**Issue by fprebolledo** [IIC2333/foro-2019-1#160]
Hola de nuevo, estaba revisando un examen pasado y me encontré con la siguiente pregunta, sin embargo, no entiendo porqué los tamaños de las subredes son esos.
![imagen](https://user-images.githubusercontent.com/26394880/60066013-d4904000-96d3-11e9-9651-0cddfedd1edc.png)
Gracias.

**Comment by cruz** [comment]
`201.10.0.0/18` corresponde a dejar 14 bit para el _host_. La respuesta de esa pauta está incorrecta. Debería ser 2^14 - 2.

`201.10.0.0/21` corresponde a dejar 11 bit para el _host_. Ese valor también está incorrecto :( ... debería ser 2^11 - 2.

Lo bueno es que esos errores no influyen en la respuesta correcta, que siguen siendo `201.10.0.0/21`
