### ISSUE TITLE
Hola! (referencia a comentario en issue)

### ISSUE THREAD

**Issue by LuisFros** [IIC2333/foro-2019-1#161]
Hola!
En la misma pregunta de Subredes IP, creo que hay respuestas incorrectas. 

Por ejemplo, la pregunta (ii) "¿Cuál es la mayor IP que se puede asignar en esta red?" y "¿Cuál es la dirección de broadcast de esta red?"
Los mismo con la pregunta (iii) "¿Cuál es la dirección de broadcast de esta red?"
(Hay otras preguntas que tambien estan incorrectas )

He confirmado con fuentes externas y los valores que encontre deberian estar correctos. 

No puedo poner los resultados aca por razones obvias, pero me gustaria saber si efectivamente estan incorrectos.
Fuente: [Link](http://jodies.de/ipcalc)
Gracias

_Originally posted by @LuisFros in https://github.com/IIC2333/foro-2019-1/issues/158#issuecomment-505484523_

**Comment by cruz** [comment]
Hola Luis.
Ayer los revisé. Puedes mandarme por mail los quue estarían mal?

**Comment by LuisFros** [comment]
Si seguro, ahora los mando. Gracias

**Comment by cruz** [comment]
OK. Están corregidos esos problemas. Gracias por el aviso @LuisFros

**Comment by LuisFros** [comment]
Perfecto, muchas gracias!
