### ISSUE TITLE
Examen - Permiso para salir brevemente

### ISSUE THREAD

**Issue by NachoCasta** [IIC2333/foro-2019-1#163]
Hola!

Tengo una presentación a las 10:30 de Web (Entrega final). Pensaba entregar 30 minutos antes el examen (o cuando mis amigos me vinieran a avisar) para ir a hacerla, pero ahora que me enteré que el examen dura 3 horas, quería preguntar si sería posible salir durante los 15 minutos que dure la presentación y volver a entrar (quizás algún ayudante me puede acompañar o les dejo mi teléfono o lo que se les ocurra para que sea posible).

Por favor🙏🏼

Se los agradecería muchísimo!

**Comment by lukassr** [comment]
Hola,

Lamentablemente no podemos permitir que salgas y vuelvas a entrar a la sala. Sin embargo, si bien el examen dura 3 horas, está pensado para ser respondido en 2 horas. 

Podrías hablar con el profesor de Web para que puedan presentar unos minutos más tarde,  o al final de todos los grupos.

Saludos!

**Comment by NachoCasta** [comment]
Si lo intente pero nos dijo que no 😢. Gracias de todas maneras!
