### ISSUE TITLE
T4 - duda "internet"

### ISSUE THREAD

**Issue by malopez16** [IIC2333/foro-2019-1#164]
Hola!
Con respecto al enunciado de la t4:

> Para modelar el acceso a Internet, ponga un servidor con IP estática y servidor web, así como un PC normal con otra IP estática que representen internet.

No logro entender la abstracción de internet que se pretende buscar en la tarea. ¿Internet serían entonces sólo un servidor y un PC?¿Pueden ser más componentes, además de estos dos? ¿Tienen que poder pasar paquetes a través de ellos si o si para comunicarse entre redes (vale decir, si envío un paquete por internet, obligatoriamente pasan por ellos dos o podría meter un router por ahí? 

Tal vez se hace referencia con "estar conectado a internet" como si me puedo meter a la página web desde cualquier PC (lo que suena más o menos lógico), pero el hecho de tener que agregar otro PC me deja con la duda. No logro entender su objetivo.

Gracias, saludos

**Comment by nivek0o0** [comment]
Hola @malopez16 

> ¿Internet serían entonces sólo un servidor y un PC?

Sí, la idea es modelar todas las páginas web del mundo en 1 servidor web y todos los hosts del mundo en 1 solo PC.

> ¿Pueden ser más componentes, además de estos dos? 

Sí, pero no es necesario. Lo único que necesita esta pequeña subred que simula internet es un router que dirija su tráfico.

> ¿Tienen que poder pasar paquetes a través de ellos si o si para comunicarse entre redes (vale decir, si envío un paquete por internet, obligatoriamente pasan por ellos dos o podría meter un router por ahí?

No, los paquetes entre las subredes de la Universidad y LAN's no deben pasar por ahí, ya que dicha subred que simula internet está pensada como una especie de endpoint, como si estuviese en otro país.. El tráfico entre redes puedes suponer que pasa a través de un router propiedad de un ISP nacional.

> el hecho de tener que agregar otro PC me deja con la duda. No logro entender su objetivo.

La idea de tener ambos componentes es que puedan probar dos tipos de comunicaciones, **ping** hacia el PC y obtener una **página web** desde el servidor.

**Comment by malopez16** [comment]
Gracias!
