### ISSUE TITLE
T4 - emulador WLAN

### ISSUE THREAD

**Issue by kdroppelmann** [IIC2333/foro-2019-1#166]
Hola, se puede usar un emulador de WLAN para conectar las LAN al router superior?

**Comment by kdroppelmann** [comment]
Y se puede alternativamente conectar el router superior a través de un switch a los routers de las lan?

**Comment by nivek0o0** [comment]
Hola @kdroppelmann 

Pueden usar lo que deseen siempre que al final se cumplan los requerimientos de las redes.
