### ISSUE TITLE
T4 Router que no se quieren conectar

### ISSUE THREAD

**Issue by Dunkan1** [IIC2333/foro-2019-1#168]
Tengo dos routers que intento conectar pero no puedo, y no logro encontrar el error

![image](https://user-images.githubusercontent.com/26102365/60534938-f3449700-9cd0-11e9-97d8-5f6f1fb4dc2d.png)

Conf. del de arriba
![image](https://user-images.githubusercontent.com/26102365/60535007-1c652780-9cd1-11e9-91f6-86bfd8b13052.png)

Conf. del de abajo
![image](https://user-images.githubusercontent.com/26102365/60535031-2d159d80-9cd1-11e9-8749-5bd43a6d80e4.png)

Desde ya gracias

**Comment by cilopez** [comment]
¿Probaste conectandolos por cables serial?, a mi me funciono asi nomas

**Comment by lukassr** [comment]
Hola!

Tal como dice @cilopez , prueba cambiando el tipo de cable.

Saludos!
