### ISSUE TITLE
T4 Router usado

### ISSUE THREAD

**Issue by Dunkan1** [IIC2333/foro-2019-1#169]
me he dado cuenta que cuando conecto dos routers entre fa1/1 y fa1/0 no se conectan

![image](https://user-images.githubusercontent.com/26102365/60550907-82fd3c00-9cf7-11e9-9a22-8761edfe023c.png)

pero si lo hago entre fa1/1 y fa0/1 si,

a los routers que use[2811] les tuve que agregar una entrada [NM-2FE2W] porque me faltaban
![image](https://user-images.githubusercontent.com/26102365/60550967-b63fcb00-9cf7-11e9-8a35-e61e408a6230.png)

 porque puede ocurrir esto? y como puedo arreglarlo?

**Comment by lukassr** [comment]
Hola!

No sabría muy bien responderte por qué no se conecta. Quizás hay algun valor mal ingresado, o los puertos de conexión entre los routers no permite que se conecten.

Sin embargo, si tienes la conexión entre fa1/1 y fa0/1 y puedes hacer las otras conexiones que se piden, no habría problema.

Saludos.
