### ISSUE TITLE
Dudas sobre IP's

### ISSUE THREAD

**Issue by ajahr95** [IIC2333/foro-2019-1#170]
Hola tengo algunas dudas sobre las IP's entregadas para la T4:

1) En las consideraciones dice "En la negociación con el proveedor de internet, la Universidad consiguió el bloque de direcciones públicas 23.16.40.0/29.". Esta mascara de 29 nos permite 3 bits para hosts, lo que es equivalente a 5 ips de uso posible. Por otro lado, en la descripción de la red eduroam dice "Esta red debe soportar por lo menos 65536 dispositivos conectados de manera inalámbrica". Esto me genera confusión, ya que con 5 ips no puedo tener 65536 hosts, ya que para eso necesitaría una mascara de menos bits. ¿Dónde se ocupan estas 5 ips entonces? ¿En los servidores, routers o qué cosa? Si fuera uno de los últimos casos, ¿La red eduroam no tendría conexiones directas, sino que todo pasaría por la red DCC? Pero al mismo tiempo se especifica que la red DCC soporta conexiones alámbricas e inalámbricas y solo se necesita dar soporte a 512 hosts.

2)  También no se si pueden aclarar lo de las direcciones públicas y privadas mencionadas en las siguientes lineas en la sección de LAN. ¿Las públicas se deben usar para los routers y las privadas para los servidores DHCP?

"El proveedor de internet asegura que cada una de estas redes está configurada con un bloque de direcciones privadas 192.168.0.0/22, donde el router toma la primera IP del bloque. También asegura que cada uno de estos routers cuentan con una IP pública en el bloque de direcciones 23.16.32.0/20, donde la primera dirección está reservada para un router superior que se encarga de direccionar las conexiones a internet y de la interconexión con otras subredes del país."

3) ¿Es necesario incluir un ISP en nuestra red?

**Comment by lukassr** [comment]
Hola.

1. Tienes que ver la forma de cómo obtener esa cantidad de hosts con menos IPs que hosts. Hay muchas formas de hacer la configuración de las redes. Mientras se cumplan los requisitos, no habría problema.

2. Correcto, la pública para routers y privadas para DHCP.

3. Si el requerimiento es tener acceso a Internet, pueden o bien incluir un ISP o simular que la red tiene acceso a Internet, y que es distinta a las otras.

Saludos.
