### ISSUE TITLE
Eduroam - You shall not pass!

### ISSUE THREAD

**Issue by jmwielandt** [IIC2333/foro-2019-1#171]
Hola!

Hablé con el profe y me dijo que hiciera issue. 

En el enunciado se dice que las lan de los alumnos solo deben poder acceder a la subred del DCC y no al resto de eduroam. Sin embargo, supongo que es incorrecto hacer que solo puedan entrar mensajes hacia eduroam desde afuera y se descarten todos los demás.

![image](https://media.giphy.com/media/xTiTnhnS1kQKfgpAHK/giphy.gif)

¿Cómo se puede distinguir la LAN de un alumno en su casa (cuya ip pública puede ser cualquier cosa) vs otro tipo de servicios que sí deben poder ser accedidos desde el interior de eduroam-no-dcc? Por ejemplo, un vídeo de youtube, todos los paquetes no serían para la subred DCC y por tanto serían descartados.

![image](https://user-images.githubusercontent.com/37153467/60610244-63b2ed00-9d91-11e9-97b8-dc08bb4abe91.png)

Sé que es muy encima pero nunca es tarde para preguntar uwu

Halp 😢

**Comment by nivek0o0** [comment]
Hola @jmwielandt 

En ese caso se debería configurar el router de entrada a la Universidad para que permita paquetes entrantes de determinados host específicos (youtube, facebook, coursera, github, etc) o bien denegar explícitamente la entrada de los paquetes que vayan a eduroam y provenientes de las LAN de los alumnos (en cuyo caso los alumnos deberían registrar previamente su dirección IP para tener acceso a la subred dcc, similar a como se hacía antes en el portal uc registrando la mac).

Los routers modernos son bastante capaces y altamente configurables, lo que te da el poder de permitir/denegar el tráfico desde X hacia Y, para cualquier combinacion de X,Y.

Pero todo esto no es necesario para esta tarea, ya que es una situación ficticia. Pueden asumir que no existen más subredes que las mencionadas, es decir, nada entrará a la U desde youtube ni nadie dentro querrá acceder a youtube.
