### ISSUE TITLE
N: Cantidad de Ráfagas de la CPU 

### ISSUE THREAD

**Issue by nfbalbontin** [IIC2333/foro-2019-1#18]
Hola, qué tal? 
Quizás es medio básico pero, no entiendo cuál es la función del N de cada proceso - cantidad de ráfagas de la CPU -. 
Gracias.

**Comment by nivek0o0** [comment]
Hola,
la función de ese parámetro es básicamente ayudarte a saber cuántos números debes leer hacia la derecha en esa línea.
