### ISSUE TITLE
Estado del Proceso

### ISSUE THREAD

**Issue by beayancan** [IIC2333/foro-2019-1#19]
Durante la simulación los procesos pasan por estados RUNNING, WAITING, READY, FINISHED ¿Es posible que agreguemos otros estados además de este para hacer cierta diferenciación?

**Comment by Geeermy** [comment]
¡Hola!

Si así lo deseas, puedes hacerlo, pero no pueden faltar los que mencionas.

¡Éxito!

**Comment by beayancan** [comment]
Gracias!
