### ISSUE TITLE
Bloqueos e interrupciones

### ISSUE THREAD

**Issue by GabrielLyonB** [IIC2333/foro-2019-1#20]
Tengo una duda conceptual ya que no me cuadran los resultados en estado _preemptive_. ¿Cuando hablan de bloqueo e interrupciones se refieren a lo mismo?, ya que dice en el enunciado que si un proceso termina su ráfaga al mismo tiempo que el _quantum_ se termina, entonces debe bloquearse también, con esto se refieren a que debe aumentar el número de interrupciones también?

Muchas gracias!

**Comment by nivek0o0** [comment]
Hola,
efectivamente en el enunciado **bloqueo** e **interrupción** se refieren a lo mismo, y corresponde al caso en que la CPU fuerza al proceso a salir porque se acabó el quantum, que es distinto a que el proceso salga _voluntariamente_.
La respuesta a tu segunda pregunta es **sí**, la estadística de interrupciones que se pide para el output corresponderá a la cantidad de veces que el proceso consumió todo el quantum.

**Comment by GabrielLyonB** [comment]
Gracias

**Comment by nivek0o0** [comment]
Por otra parte, descubrimos un pequeño error en las estadisticas del test y lo solucionaremos a la brevedad.

**Comment by GabrielLyonB** [comment]
¿En el `out3.txt`? porque no me cuadra jajaj

**Comment by nivek0o0** [comment]
En todos los outputs fue modificado el turnaround time.
Saludos

**Comment by Sgwa** [comment]
@nivek0o0 
en los outpust que subieron solo veo modificaciones en el out3.txt, eso esta bien?, los otros dos se mantienen?

**Comment by nivek0o0** [comment]
Se acaban de actualizar todos jeje. 
Disculpa los inconvenientes.
