### ISSUE TITLE
Mensaje de Error Valgrind

### ISSUE THREAD

**Issue by auirarrazaval** [IIC2333/foro-2019-1#21]
Hola! al correr mi codigo por valgrind me sale el siguiente error:
![image](https://user-images.githubusercontent.com/31079536/55294094-2a569400-53d4-11e9-9f1e-f4369b0ca95b.png)
Y la verdad es que no entiendo a que se refiere. ALguna idea de que puede ser?

**Comment by IchottMano** [comment]
Hola!

Lo mas probable es que hayas intentado acceder (o liberar) un puntero NULL, el cual usualmente apunta al Address 0x0.

Valgrind usualmente te dice que línea de tu código fue la que intentó acceder a esa dirección, para poder debuguear.

Saludos!

**Comment by auirarrazaval** [comment]
![image](https://user-images.githubusercontent.com/31079536/55294245-eebcc980-53d5-11e9-9502-accda856851c.png)
El error me lo tira en la linea 49, entonces si el ```fopen(file, "r")``` retorna un puntero nulo, no es necesario hacer ```fclose(file)```?

**Comment by IchottMano** [comment]
Exacto, ya que cuando haces fclose() intentas acceder a un puntero que no existe (el NULL).
Si el puntero que te entrega es nulo, puedes asumir que no debes liberarlo (cerrarlo), ya que el NULL significa que no se pudo abrir.

Saludos!

**Comment by auirarrazaval** [comment]
Perfecto, Muchas gracias!
