### ISSUE TITLE
Duda conceptual Scheduling (tarea)

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2333/foro-2019-1#22]
Hola,

Pequeña duda: Si tengo un proceso que está en WAITING en la iteración i, y es la última iteración que le queda para estar en WAITING, y además es la última iteración que le queda a al proceso que está en RUNNING. ¿Puede ese proceso que está en WAITING pasar en la siguiente iteración a estado RUNNING? ¿O debe pasar primero por READY y luego, en itraciones posteriores, pasar a RUNNING?

**Comment by IchottMano** [comment]
Hola!

Puede pasar a RUNNING inmediatamente, ya que puedes pensar que el proceso pasará a READY al inicio de la siguiente iteración y luego de esto la CPU será la que elija que proceso dejar entrar.

Saludos!

**Comment by jorgeriesco** [comment]
Gracias!
