### ISSUE TITLE
Reporte T01 - P3

### ISSUE THREAD

**Issue by malopez16** [IIC2333/foro-2019-1#23]
Hola! En la pregunta 3 del Reporte, se consulta

> ¿Cuál versión del algoritmo se comporta mejor...

Acá se está haciendo referencia a cuál de las 2 versiones enunciadas en las preguntas anteriores (o sea single core - multi core) o a preemptive - non preemptive? 

Gracias!

**Comment by IchottMano** [comment]
Hola! 

La pregunta se refiere a preemptive/non-preemptive.

Saludos!

**Comment by malopez16** [comment]
Gracias :)
