### ISSUE TITLE
Input de los tests

### ISSUE THREAD

**Issue by ariel-m-s** [IIC2333/foro-2019-1#24]
Hola! 

Qué _input_ le corresponde a cada test de la página del curso? (_preemptive_, _non-preemptive_, qué _quantum_)

Saludos.

**Comment by IchottMano** [comment]
Hola!

En la carpeta tests que les dimos hay un archivo llamado readme.txt donde se indica el input correspondiente a cada output.

Saludos!

**Comment by ariel-m-s** [comment]
Gracias!
