### ISSUE TITLE
LEAK SUMMARY

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2333/foro-2019-1#25]
La idea es tener todo en cero? 
Está bien esto?
LEAK SUMMARY:
==20359==    definitely lost: 0 bytes in 0 blocks
==20359==    indirectly lost: 0 bytes in 0 blocks
==20359==      possibly lost: 0 bytes in 0 blocks
==20359==    still reachable: 552 bytes in 1 blocks
==20359==         suppressed: 0 bytes in 0 blocks

**Comment by IchottMano** [comment]
Hola!

Si, deberia estar todo en cero, ahi todavía te faltan liberar 552 bytes de memoria.

Saludos!
