### ISSUE TITLE
input test

### ISSUE THREAD

**Issue by fprebolledo** [IIC2333/foro-2019-1#27]
Hola! los input en lost test corresponden a una linea con cada proceso + una linea en blanco?(mi condición de ciclo depende de esto).
gracias!

**Comment by IchottMano** [comment]
Hola!

Como dice el enunciado, el input es un archivo de múltiples líneas, **donde cada una** tiene un formato, lo cual quiere decir que todas las líneas del archivo contendrán información y no habrán líneas en blanco.

Saludos!

**Comment by nivek0o0** [comment]
Hola Francisca,
¿estás leyendo el archivo con un loop para las líneas, luego utilizas alguna función de tipo scan para los primeros parámetros hasta el N, y con ese N haces otro loop para escanear los 2N-1 números restantes de esa línea?

El punto es que no es necesario saber de antemano cuántas líneas trae el archivo, ya que esas funciones de escaneo por lo general retornan el numero de _matches_ exitosos. Por lo tanto, deberás dejar de leer cuando dejen de hacer _match_.
