### ISSUE TITLE
Servidor caído (Creo)

### ISSUE THREAD

**Issue by NachoCasta** [IIC2333/foro-2019-1#29]
Hola,

Al intentar conectarme por ssh al servidor me sale el mensaje

`ssh: connect to host ing.puc.cl port 22: Resource temporarily unavailable`

Asumo que el servidor esta caído. Que puedo hacer?

**Comment by cruz** [comment]
Hola
Yo acabo de entrar y lleva 56 días contínuos arriba. ¿Estás poniendo bien el nombre? (en tu mensaje dice `ing.puc.cl`)

```
cruz@iic2333:~$ uptime
 05:07:54 up 56 days, 18:07,  4 users,  load average: 0.02, 0.06, 0.01
cruz@iic2333:~$ 
```

**Comment by frvalenzuela** [comment]
Me surge el mismo inconveniente que @NachoCasta

**Comment by IchottMano** [comment]
@frvalenzuela @NachoCasta Hola!
Por casualidad estan intentando entrar al servidor usando Windows Subsystem?

**Comment by NachoCasta** [comment]
Acabo de lograrlo.

El problema era que en el primer anuncio aparece `@iic2333@ing.puc.cl`, en el segundo `@iic2333.ing.uc.cl` y el correcto no es ninguno de esos, sino que `@iic2333.ing.puc.cl`

Gracias!
