### ISSUE TITLE
Duda AC01 - Parte: ¿Qué hace el sistema operativo?  Pregunta:  Analogías para el sistema operativo 

### ISSUE THREAD

**Issue by malopez16** [IIC2333/foro-2019-1#3]
Una de las alternativas es 

> Un sistema operativo funciona como el vendedor (CPU) que está tras el mostrador de una tienda (sistema computacional) esperando que un cliente (programa de usuario) utilice la tienda mediante el vendedor para obtener productos. 

No logro entender el rol que nos quieren expresar del sistema operativo en esta alternativa. Creo que es un tema de redacción que no entiendo. ¿Un sistema operativo funciona como el vendedor (CPU)? El vendedor es la CPU? Es el sistema operativo? La interacción es el sistema operativo?

Edit: Al seguir leyendo, tengo otra duda con otra alternativa:

>  Un sistema operativo es como el sistema burocrático de un estado (sistema computacional) con el que los ciudadanos (programas de usuario) **interactúan (llamadas al sistema)** para obtener beneficios y acceder a los recursos que el estado provee. 

Interactúan se refieren en general? Entre sí? Con la CPU?

Gracias

**Comment by cruz** [comment]
Hola,
Respecto a esta:

> Un sistema operativo funciona como el vendedor (CPU) que está tras el mostrador de una tienda (sistema computacional) esperando que un cliente (programa de usuario) utilice la tienda mediante el vendedor para obtener productos.

Lo que se refiere es que el sistema operativo es el modelo de atención. El vendedor es la CPU, y podría haber más de uno (que sería el caso de un _multicore_) que atiende a la gente (programas de usuario) y permite acceso a los recursos (los productos o servicios que se entreguen). El sistema operativo es el modelo en el cual una persona llega, solicita un servicio o producto, y solo puede accederlos a través de lo que el sistema te permita hacer. No puede llegar y autoservirse. Si la persona llega y están todos los vendedores ocupados, el sistema podría hacerte sacar un número y ponerte en una cola o tratar de "luchar" por la atención del sistema (ahí estarían los algoritmos de _scheduling_ que deciden quién va con qué vendedor), pero en cualquier caso no puedes hacer nada que el sistema no lo permita. Si no sigues las reglas el sistema operativo (mediante el componente de seguridad que podría ser un guardia), te saca del lugar (te saca de la memoria).

Espero que se entienda un poco mejor la idea.

Respecto a esta:
> Un sistema operativo es como el sistema burocrático de un estado (sistema computacional) con el que los ciudadanos (programas de usuario) interactúan (llamadas al sistema) para obtener beneficios y acceder a los recursos que el estado provee.

En este caso particular se refiere a que los ciudadanos interactúan con el sistema computacional únicamente a través de los servicios que el sistema operativo ofrece. También podrían interactuar entre ellos pero esa parte no estaba incluída aquí.

Avísame si esto ayuda.
