### ISSUE TITLE
Header Syscall Stat 

### ISSUE THREAD

**Issue by cilopez** [IIC2333/foro-2019-1#31]
Hola, realizado la actividad me surgio un par de dudas: 

-  Si una syscall tiene más de un header, ¿debemos ponerlos todos o cuál?

- Si el header de la syscall es : #include <sys/libreria.h> : ¿Cómo debo ingresarla, como libreria.h o incluyendo sys/libreria.h?

**Comment by cruz** [comment]
Hola, aunque aparece como "cerrado" aprovecho de responderla.

> Si una syscall tiene más de un header, ¿debemos ponerlos todos o cuál?

No estoy seguro si te pregunto es específicamente por lo que estábamos preguntando, o en general. Si es específicamente por la actividad, la idea es hacer `man` de la _syscall_ y averiguar ahí que _header_ es el necesario. La que te preguntamos es la que contiene la declaración de la función que ejecuta el llamado, y ésa es sólo una. Por otro lado si lo estás preguntando en general para un programa en C, hay que agregar todos los _headers_.

> Si el header de la syscall es : #include <sys/libreria.h> : ¿Cómo debo ingresarla, como libreria.h o incluyendo sys/libreria.h?

En el caso de la actividad sería `sys/libreria.h`

**Comment by cilopez** [comment]
Gracias!
