### ISSUE TITLE
Duda AC02 - Header para fork()

### ISSUE THREAD

**Issue by fdominguezclaro** [IIC2333/foro-2019-1#32]
En esta pregunta, hay que ingresar el/los resultado/s a mano. Consideraron como correctas cuando se ingresan en distinto orden las librerías?

Me parece extraño haber tenido mala esa pregunta (intenté de 3 formas distintas), dado que en muchos sitios aparecía de manera textual.

**Comment by cruz** [comment]
Hola. Se me pasó responder esta. ¿Qué contestaste? La idea era poner solo una. 

Si ves aquí: https://linux.die.net/man/2/fork, la única necesaria era `unistd.h`
