### ISSUE TITLE
[T02] - Largo máximo palabras

### ISSUE THREAD

**Issue by malopez16** [IIC2333/foro-2019-1#34]
Hola,

Es posible que asumamos que las palabras en el archivo de input tengan algún largo máximo?

Gracias, saludos

**Comment by Geeermy** [comment]
¡Hola!

Sí, definitivamente. Si se quieren ir a la segura, asuman el largo máximo de una palabra en inglés, que son 45 caracteres: https://www.grammarly.com/blog/14-of-the-longest-words-in-english/

Si se quieren ir a la segura, pueden asumir 256 caracteres por palabra.

¡Éxito!

**Comment by malopez16** [comment]
Gracias Germy!

**Comment by Geeermy** [comment]
Adicional: pueden asumir también que no habrán caracteres que no provengan del inglés, por ejemplo, la ñ.

😁

**Comment by cruz** [comment]
> Adicional: pueden asumir también que no habrán caracteres que no provengan del inglés, por ejemplo, la ñ.
> 
> 😁

Ni los acentos

**Comment by jmwielandt** [comment]
Y números? o.o

**Comment by Geeermy** [comment]
Para que no tengan problemas considerando si es una palabra o no: **no, no incluiremos números.**

**Comment by sjmunoz** [comment]
@Geeermy  Tenemos un maximo de lineas? 

Gracias!
