### ISSUE TITLE
Creacion maps y reduce

### ISSUE THREAD

**Issue by Dunkan1** [IIC2333/foro-2019-1#35]
Para la tarea los reduce deben ser creados al mismo tiempo que los maps o se puede crear todos los maps esperar su retorno y luego crear el reduce?

**Comment by IchottMano** [comment]
Hola!

No es necesario que los reduce sean creados al mismo tiempo, la idea es simplemente que uses memoria compartida para entregarles la información pertinente, por lo que es válido si los creas despues.

Sin embargo, ten cuidado, ya que no será válido que le entregues la información, por ejemplo, por medio de la memoria copiada de un **fork()**.

Saludos!

**Comment by yoavnavon** [comment]
@IchottMano Colgándome un poco de la pregunta, podemos usar la syscall pipe() para enviar datos entre procesos?

**Comment by IchottMano** [comment]
@yoavnavon Hola!

Como dice el enunciado, se evaluará el uso de **shm_get**, por lo que puedes usar un pipe, sin embargo no se asignará puntaje en la parte de comunicación entre procesos.

Saludos.

**Comment by nfbalbontin** [comment]
Una duda con respecto a lo mismo, entonces, ¿un map puede crear un reduce a partir de _fork()_ pero se tienen que comunicar a partir de memoria compartida?

**Comment by IchottMano** [comment]
@nfbalbontin Si, sin embargo debes tener **mucho cuidado** de no usar información previa del map (es decir que no puedes usar el hecho de que el reduce es hijo del map para acceder a información del padre antes que este hiciera **fork()**)

Saludos!
