### ISSUE TITLE
Manejo eficiente de memoria

### ISSUE THREAD

**Issue by fdominguezclaro** [IIC2333/foro-2019-1#36]
Hola! 
Podemos asumir que **no** nos van a llegar archivos de texto muuuuuuy grandes (que no cabrán en memoria)?

**Comment by IchottMano** [comment]
Hola!

Puedes asumir que los archivos que les entregaremos cabrán en la RAM, sin embargo intenta no cargar todo el texto de una 😅 

Saludos!

**Comment by fdominguezclaro** [comment]
Volviendo a esto, tengo una duda en la parte de threads:

Estructuré mi tarea para dividir el archivo de input en varios chunks, y que cada thread procese su chunk asociado.

Mi idea es no cargar toda la información en la RAM, pero a la larga, cada thread pedirá memoria, y finalmente de todas maneras se cargará todo el archivo.

Una opción que se me ocurrió fue que cada thread guarde su información en el disco escribiendo un archivo, pero no creo que sea una solución eficiente...

Cuál es la manera correcta de hacerlo?

**Comment by IchottMano** [comment]
Hola!

Para archivos muy grandes, probablemente existan una gran cantidad de threads que hagan map, los que idealmente no correrán **todos** al mismo tiempo, es decir que habrán threads **map** que terminarán antes de que otros comiencen, liberando su memoria y permitiendo que no cargues mucha memoria **simultáneamente**.

Saludos!

**Comment by fdominguezclaro** [comment]
Y usar `mmap` hace el trabajo más eficiente?
