### ISSUE TITLE
Cantidad de reduce

### ISSUE THREAD

**Issue by valerojasm** [IIC2333/foro-2019-1#37]
Hola!

No me quedó muy claro si es necesario que haya más de un reduce en la tarea - me hace sentido que haya un solo reduce para los distintos maps que van a haber, y que en el fondo este junte todos los valores de retorno y escriba el archivo de output pedido, pero no sé si esto está correcto. 

Muchas gracias!

**Comment by IchottMano** [comment]
Hola!

Si bien no es 100% necesario que tengas múltiples reduce, como se dijo en la ayudantía te puede ayudar en el caso que tengas demasiados **map** y puedas de alguna manera paralelizar el intercambio de información.

Saludos!
