### ISSUE TITLE
Ayudantía T2

### ISSUE THREAD

**Issue by acrojas2** [IIC2333/foro-2019-1#39]
Hola, 
Escribo para saber si es que hay posibilidad que el viernes se haga un horario de consulta extraordinario para dudas sobre la tarea 2. Sé que harán una el lunes, pero por lo menos a mi me afecta bastante entender bien y arreglar las cosas en un plazo tan próximo a la entrega. Es decir, cambiar cosas en último momento aumenta el riesgo de tener  _segmentation fault_ y arreglarlos me toma aun más tiempo. 

Ojalá consideren mi petición, ya que consulté en el curso y varios querían la ayudantía el viernes en lugar del lunes, pero como los que votaron por pedir el enroque no es la mayoría hago esta petición a título personal, pero beneficiaría a más personas que a mí. 
Eso! Saludos.

**Comment by IchottMano** [comment]
Hola!

Hemos decidido hacer un horario de consultas extraordinario este viernes, les diremos los detalles mas tarde a través de un aviso en el Siding :D

Saludos!

**Comment by malopez16** [comment]
Pucha, muchos tenemos tope con Orga (plenarias, obligatorias, y con sólo un horario para tooodas las secciones: V2, gracias dipre) y nos quedamos sin opción de ir los viernes. Se hizo una muy mini votación en un chat de telegram (n = 15) y la mayoria votó lunes :(
Creo que ya es muy tarde.. pero no había alcanzado a leer esto y asumo que otros tampoco :(..
En fin, creo que a todos nos serviría un poco de ayuda para la tarea y estaríamos felices de ir, para que no piensen que en realidad no le estamos poniendo bueno o algo los que no podremos ir el viernes (Personalmente me ha costado harto, pero he estado trabajando todo lo posible)

**Comment by LuisFros** [comment]
Estoy en la misma situacion que @malopez16.

**Comment by Geeermy** [comment]
**Pro-tip:** Si hacen votaciones mediante una _issue_ acá y no solo en Telegram, podemos estar más al tanto de sus necesidades. :eyes: 

Cualquier tipo de ayuda que podamos otorgar antes de la entrega, obviamente no la vamos a obviar. Lo estaremos conversando con el equipo. 😁

**Comment by jmopaso** [comment]
Tengo el mismo problema que @malopez16 y @LuisFros, de igual forma me gustaría saber si se mantiene el horario de consultas extraordinario de mañana (Viernes 12) en la sala Álvaro Campos.
