### ISSUE TITLE
Memoria compartida con estructuras

### ISSUE THREAD

**Issue by jvlara** [IIC2333/foro-2019-1#40]
Tengo una lista ligada, en la cual cada nodo cumple la función de ser un nodo simulado de diccionario, al momento de compartir esta lista ligada entre los procesos lo que sucede es que al crear un nodo este solo se crea en la memoria de ese mismo proceso y se almacena el puntero de este en la lista ligada, entonces no se traspasa la información al programa principal.
¿Como podría hacer para que si funcionara?

**Comment by jvlara** [comment]
¿Sería mas recomendado compartir un char y tener una convension para la informacion de los distintos forks() y en el reduce leer ese char considerando el criterio?

**Comment by IchottMano** [comment]
Hola!

Una posibilidad es hacer lo que planteas, mientras que tambien podrías guardar tus estructuras dentro de la memoria (puedes castear la memoria compartida para que se vuelva un puntero a lo que tu quieras).

Saludos!
