### ISSUE TITLE
Test T2 posiblemente con errores 

### ISSUE THREAD

**Issue by jvlara** [IIC2333/foro-2019-1#41]
Revisando el output de los ejemplos me encontré con una gran diferencia en la cantidad total de varias de las palabras en text.txt (buscando con vsc) en consideración a los resultados que nos dieron. 
Por ejemplo con la palabra far, donde buscando con vsc sin case sensitive sale 384 y en el output 1787
![imagen](https://user-images.githubusercontent.com/26396425/56007160-c1a9ca00-5ca5-11e9-9e1c-bf5f6bf72346.png)
![imagen](https://user-images.githubusercontent.com/26396425/56007164-c7071480-5ca5-11e9-8a0f-ad95db1ca9d4.png)
¿Es esto un error?

**Comment by IchottMano** [comment]
Hola!

Efectivamente habia un pequeño error en una línea de nuestro generador de tests, el cual ya se encuentra arreglado.
Mas tarde subieremos los test corregidos.

Muchas gracias por hacernos saber esto!
Saludos!

**Comment by Nicolasvegam** [comment]
en ese caso tendrías que buscar " far " y no "far" porque de igual manera se podría encontrar otra palabra como "ne**far**ious", o también se considera que se repita la palabra dentro de otra?

**Comment by IchottMano** [comment]
@Nicolasvegam Hola!

No, no se considera una palabra dentro de otra. 

Saludos!
