### ISSUE TITLE
T2: Largo maximo de una linea en los test con los que evaluaran.

### ISSUE THREAD

**Issue by jvlara** [IIC2333/foro-2019-1#42]
Hola, quería saber si se puede asumir a priori el largo máximo de la linea más larga de un archivo, ya que la función de C que lee las lineas de un archivo ocupa un buffer que necesita este valor, en Text2.txt la linea mas larga es de 1060 caracteres ¿Podemos asumir que no superara los 1100 caracteres?.

**Comment by LuisFros** [comment]
Una sugerencia, puedes usar “realloc()” para no tener que hacer ese tipo de supuestos. Lo han mencionado los ayudantes del curso y es muy útil.

**Comment by IchottMano** [comment]
Hola!

Como dicen anteriormente no se puede asumir a priori el largo máximo de las líneas, pero como dicen anteriormente puedes usar **realloc** para aliviar el problema o también puedes leer hasta donde te dé el buffer y cortar en un espacio de ser necesario.

Saludos!
