### ISSUE TITLE
Libreria de Hash Table

### ISSUE THREAD

**Issue by LuisFros** [IIC2333/foro-2019-1#43]
Podemos usar una libreria para implementar una tabla de hash?
Por ejemplo [Khash](https://github.com/attractivechaos/klib)

**Comment by IchottMano** [comment]
Hola!

Pueden usar tanto librerías de libc (Librería Estándar de C) o de la librería POSIX de C, por lo que no podrían usar Khash.

Saludos!

**Comment by LuisFros** [comment]
Ok, Gracias!
