### ISSUE TITLE
Uso de código externo para Diccionario

### ISSUE THREAD

**Issue by B-Dominguez** [IIC2333/foro-2019-1#44]
Hola, quisiera saber si hay algún problema con el uso de código disponible en internet (GitHub Gist) como base para la implementación de un diccionario (para almacenar resultados de los conteos de palabras), citando la fuente y fecha en el código.
Gracias!

**Comment by IchottMano** [comment]
Hola!

Mientras cites la fuente, no hay problema con que ocupes tal código.

Saludos!
