### ISSUE TITLE
Duda enunciado

### ISSUE THREAD

**Issue by LuisFros** [IIC2333/foro-2019-1#45]
![image](https://user-images.githubusercontent.com/21247721/56073449-1286f480-5d72-11e9-8c80-b6b24fb7deab.png)

El primer punto debe ser con MapReduce? (Dado que dice "**MapReduce para procesar un texto cualquiera**").
El punto 2 y 3 estan siendo explicitos con el uso de MapReduce

**Comment by Geeermy** [comment]
¡Hola Luis!

Sí. Al final se hace uso explícito de `MapReduce` en los puntos (2) y (3) para que noten que pueden usar dicho modelo haciendo uso de los resultados que obtienen en (1). No fue escrito así para dar a entender que uno se resolvía con `MapReduce` y los otros no.

¡Que estés bien! :)

**Comment by LuisFros** [comment]
Gracias!,
Me quedo claro
