### ISSUE TITLE
Notas T1

### ISSUE THREAD

**Issue by fprebolledo** [IIC2333/foro-2019-1#46]
cuando estarán las notas de la tarea 1?

**Comment by Geeermy** [comment]
¡Hola Fran!

El plazo legal es de 15 días hábiles (23 de abril si se considera que subieron sus tareas el 2 del mismo mes), pero haremos el mayor esfuerzo posible para poder tenerlas antes. 

Espero poder tenerles noticias de esto durante la semana y esperamos tu comprensión jeje.😅
