### ISSUE TITLE
Modo de simulación

### ISSUE THREAD

**Issue by GabrielLyonB** [IIC2333/foro-2019-1#5]
La idea de la simulación es hacerla de manera continua?, es decir, simulo avanzar de a una unidad de tiempo. (La otra opción es por eventos discretos).

**Comment by Geeermy** [comment]
¡Hola!

No importa mucho cómo lo hagas realmente, siempre y cuando al final de la simulación se tenga el mismo resultado.

¡Que estés bien! :)
