### ISSUE TITLE
Intermediario entre map y reduce

### ISSUE THREAD

**Issue by ariel-m-s** [IIC2333/foro-2019-1#50]
Hola!

¿Puedo tener un thread o proceso (dependiendo de qué parte de la tarea hablamos) que actúe de intermediario entre los ```map``` y los ```reduce```? Por ejemplo, que tome todas las salidas de los ```map``` y se los entregue de manera ordenada a los ```reduce```. ¿O es estríctamente necesario que estos interactúen de manera independiente?

Saludos

**Comment by IchottMano** [comment]
@ariel-m-s Hola!

Si, puedes hacer eso siempre y cuando los procesos se comuniquen con memoria compartida.
Para los threads tampoco hay problema.

Saludos!

**Comment by ariel-m-s** [comment]
Gracias @IchottMano .
