### ISSUE TITLE
Error en función shmget

### ISSUE THREAD

**Issue by paula-ds** [IIC2333/foro-2019-1#51]
Hola, tengo un problema con las flags que recibe la función, estaba probando el código de la ayudantía y me tira este error

![error](https://user-images.githubusercontent.com/30679494/56097215-4de30980-5ebf-11e9-9c75-389f436f70ff.png)

 Uso Cygwin en Windows 8.1, Atom y tengo esto:

#include <sys/shm.h>
#include <sys/ipc.h>
#include <wait.h>
#include <pthread.h>
#include <sys/types.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include <errno.h>
#include <signal.h>

Cualquier ayuda lo agradecería

**Comment by IchottMano** [comment]
Hola!

Tambien puedes intentar con
```C
shmget( key, 2048, IPC_CREAT | 0666 )
```
Por favor dime si esto te funciona.

Saludos!

**Comment by paula-ds** [comment]
Ahí me funcionó, gracias!
