### ISSUE TITLE
Formato output

### ISSUE THREAD

**Issue by lucasmarinb** [IIC2333/foro-2019-1#52]
¿Las palabras en el output tienen que estar en minúsculas? Entiendo que el programa no debe ser
case-sensitive, pero el enunciado no explicita el formato de las palabras en el output.

Saludos.

**Comment by IchottMano** [comment]
Hola!

El output, como tu programa, no es *case-sensitive*, por lo que no importa si hay mayúsculas en tu output.

Saludos!
