### ISSUE TITLE
Problemas con shmget 

### ISSUE THREAD

**Issue by Nicolasvegam** [IIC2333/foro-2019-1#55]
Llevo varios días tratando de compartir la información de un proceso al otro. Cuando lo hago, lo hago mediante un loop pero el reduce sólo toma una porción de los que le llegan y aleatoria. He buscando como enviar múltiple información por shmget pero no he encontrado cómo. Por lo que entendí tampoco se puede compartir una estructura completa.

**Comment by IchottMano** [comment]
Hola!

Todos los procesos estan usando la misma memoria compartida? Recuerda que de ser así cualquier proceso puede llegar y sobreescribir el segmento de memoria, sin aviso.
De no ser el caso, puedes intentar implemetar una especie de sincronización usando señales **kill()**.

Finalmente, es posible compartir estructuras completas, si casteas el puntero a memoria compartida o una parte de este, para luego rellenar tu mismo las nuevas estructuras creadas.

Saludos!
