### ISSUE TITLE
Petición de más tiempo T2

### ISSUE THREAD

**Issue by frvalenzuela** [IIC2333/foro-2019-1#56]
Hola!

Escribo para saber si es que hay posibilidad de extender el plazo de entrega de la tarea 2. En lo personal necesito más tiempo porque tengo un cumulo de entregas y evaluaciones en los próximos días que me dificultará mucho tener terminada mi tarea a tiempo, y deberé optar por entregar la tarea tarde, que aún sabiendo la nueva formula, quisiera tener el chance de entregarla a tiempo, si es que fuese extendido el plazo.

Estoy consciente de que los plazos fueron dados hace bastante días, pero aún así no pierdo nada en preguntar.

Saludos!

**Comment by movaldivia** [comment]
Estoy en la misma situación de Felipe D:

**Comment by jmwielandt** [comment]
Estoy igual, solo que también la semana pasada llena 😭😭

**Comment by fnquinteros** [comment]
Adhiero :(

**Comment by ariel-m-s** [comment]
Me gustaría poner en consideración dos puntos de vista.

Primero (y como mi situación en particular), no podré entregar la tarea a tiempo, pues, como sucede frecuentemente, tengo muchos _deadlines_ con los que cumplir esta semana. Me imagino que esta situación la compartimos muchos en esta universidad.

Segundo, sé que a veces puede ser feo (no sé cual es la palabra indicada) pedir más plazo para una tarea, porque como alumnos tenemos completa responsabilidad de cumplir con las evaluaciones que proponen los cursos. Sin embargo, con el plazo actual, lamentablemente, no alcanzaré a terminar y solamente aprenderé la mitad de la materia.

Con respecto a esto último, me parece que las tareas son un **gran** herramienta para digerir bien la materia del curso y es bien sabido que la carga academica no es proporcional al aprendizaje. En mi caso, toda la parte de procesos y memoria compartida está quedando fuera de mi tarea :cry: y la verdad es que me encantaría tener más plazo para que esto no suceda y pueda sentirme satisfecho con lo que hice.

Saludos 💻

**Comment by acrojas2** [comment]
Hola, 
En mi caso particular, aunque aumenten el plazo para entregar la tarea (no creo que den más de un día), de todas formas no alcanzaría a implementar lo de procesos y memoria compartida, a pesar de que el viernes fui al horario de consultas y pregunté por esto en particular, a la hora de la implementación morí en el intento. Es por eso que si se puede agregar al petitorio un horario de ayuda sería mejor y más útil el plazo extra. 
Saludos!

**Comment by lukassr** [comment]
Acabamos de enviar un aviso con la información 🙂
Se extiende el plazo hasta el viernes 19 de abril a las 14:00 hrs.
Aquellos que entreguen en el plazo original (miércoles 17 de abril a las 14:00 hrs) recibirán un bonus de +0.5 décimas.

Aprovechen este tiempo para entregar un tarea buena, bonita y de calidad 😊
