### ISSUE TITLE
strcat y fork

### ISSUE THREAD

**Issue by fprebolledo** [IIC2333/foro-2019-1#57]
Hola en mi tarea tengo un string, char a [largo]; y en este voy concatenando palabras, sin embargo luego de hacer fork() cuando imprimo esta variable, solo contiene la primera palabra. A que se debe esto?

**Comment by IchottMano** [comment]
Hola!

Podrias explicar un poco mas tu problema por favor?
Como estas concatenando las palabras? Lo haces antes o despues del fork?
Donde estas guardando las palabras concatenadas?

Saludos!
