### ISSUE TITLE
Lectura archivo input en reduce

### ISSUE THREAD

**Issue by B-Dominguez** [IIC2333/foro-2019-1#58]
Hola, para leer el input lo hice primero en el reduce (que crea los map) y este divide y entrega palabras a cada map para que las cuente. Quisiera saber si se esperaba necesariamente que la lectura de archivos sea por separado en los map.
Además, esto hace que la creación del reduce y los map no sea exactamente simultánea, pero me parece que no es un problema. 
Gracias!!

**Comment by IchottMano** [comment]
Hola!

Como me explicas tu implementación está bien, se espera que la lectura del archivo sea en un solo proceso o thread y este le entregue la información (palabras) a los maps.

Saludos!
