### ISSUE TITLE
Parte II y III

### ISSUE THREAD

**Issue by Dunkan1** [IIC2333/foro-2019-1#60]
queria quedar claro con esta parte

> (1) Cantidad de veces que se repite una palabra en el texto.

> (2) Palabras que se repiten la misma cantidad de veces, aplicando MapReduce al resultado en (1).

> (3) Cantidad de veces que se usan palabras del mismo largo, aplicando MapReduce al resultado en (1).

para (2) y (3) se refiere a que ejecutemos el map-reduce de (1) y sobre ese ejecutemos otro?

o podemos solo modificar el reduce de (1)

**Comment by IchottMano** [comment]
Hola!

Pueden hacerlo como ustedes quieran, la idea de el *aplicando MapReduce al resultado en (1)* era a modo de darles un pequeño hint para como hacerlo.

Saludos!

**Comment by Dunkan1** [comment]
o genial gracias

**Comment by B-Dominguez** [comment]
### Como esta Issue está marcada como resuelta, abrí una nueva (#62 ) con la siguiente duda
Hola, se espera que se utilicen múltiples threafs (forks) para pasar de (1) a (2) o (3)? Es decir, se espera que hayan varios map también en (2) y (3) aún si se usa (1) como base? Por la naturaleza de (2) y (3), sobre todo en (2) por el set de palabras, me parece que es mejor hacer un reduce sobre el resultado completo de (1).
Gracias!

**Comment by nfbalbontin** [comment]
Sobre esto mismo con respecto a los procesos. Entonces para 2 y 3 ¿podemos realizar un reduce sobre el reduce de 1 sin la necesidad de tener que generar un mapeo nuevamente?
