### ISSUE TITLE
Funcionalidad (2) solo en un reduce sobre (1)

### ISSUE THREAD

**Issue by B-Dominguez** [IIC2333/foro-2019-1#62]
Hola, considerando que en la funcionalidad (2) hay que imprimir el set sin repetición de las palabras para cada cantidad de repeticiones, me parece más eficiente procesar en un solo reduce el resultado de 1. Esto ya que hacerlo en muchos map requriría comparar cada palabra del set (para no repetirla) cada vez que se agregan los resultados.

Quisiera saber si va contra lo que se espera el hacerlo en un solo reduce sobre (1).

Gracias!

**Comment by Geeermy** [comment]
¡Hola!

No, no va en contra, para nada. En teoría, estás ocupando _maps_ y _reduces_ en la solución, por lo que está bien. :-)

¡Éxito!
