### ISSUE TITLE
Actividades pistas al errar

### ISSUE THREAD

**Issue by acrojas2** [IIC2333/foro-2019-1#63]
Hola: 
En la AC03 después de cierta pregunta ya no daban pistas al errar y me paso que acabé los intentos sin tener idea porqué mis respuestas podían estar malas . ¿Podrían volver al sistema de las pistas? A mí en lo personal me servía para saber porqué una respuesta que creía correcta en realidad no lo era.
Eso, saludos!

**Comment by Geeermy** [comment]
¡Hola!

No es que se haya dejado de usar el sistema de pistas. Lo más probable es que las preguntas que hayas respondido simplemente no las hayan tenido.

Conversaremos con el equipo para ver el tema en detalle y hacer algo al respecto.

¡Que estés bien!

**Comment by cruz** [comment]
Hola,
La idea es que haya de estas pistas en la mayoría de las preguntas para apoyar su aprendizaje. Si algunas no tienen es probable que nos haya faltado actualizarlas. En ese caso es bueno que nos avisen lo antes posible para poder revisarlas.
¡Saludos!
