### ISSUE TITLE
Puntaje Output Correcto

### ISSUE THREAD

**Issue by nfbalbontin** [IIC2333/foro-2019-1#65]
Una pregunta bastante desesperada pero, ¿el puntaje del output correcto es sin importar el método que se llevó a cabo? es decir, si logro generar un output correcto para el primer método y lo ocupo como el output del segundo, ¿se obtiene el puntaje? 
Gracias!

**Comment by IchottMano** [comment]
@nfbalbontin Hola!

El puntaje de output correcto se otorga, siempre y cuando tu tarea funcione debidamente, es decir que obtenga el output correcto a través de threads o procesos, independiente de tu implementación de MapReduce.

Saludos!
