### ISSUE TITLE
Informe Tarea 2

### ISSUE THREAD

**Issue by cataschaufler** [IIC2333/foro-2019-1#67]
Existe alguna forma de utilizar otros datos (entregados por ustedes o de otros alumnos) para así poder hacer el infrome a pesar de que no funcione correctamente alguno de los programas? Ya que la implementacion  con procesos no me funciona correctamente y lamentaría mucho tener un 1 y que baje más mi nota de la tarea, a pesar de dedicarle tanto tiempo.

**Comment by IchottMano** [comment]
Hola!

En el caso que no seas capaz de implementar la sección de threads o procesos, deberán comparar **teóricamente** las dos implementaciones, argumentando cual es mas eficiente y por qué.

Saludos!

**Comment by cataschaufler** [comment]
Ok, Muchas gracias!!
