### ISSUE TITLE
Estructura Cola de Procesos

### ISSUE THREAD

**Issue by FelipeApablaza** [IIC2333/foro-2019-1#7]
En el enunciado se indica que se debe tener una estructura de cola que reciba los procesos. Mi pregunta es si se evaluará la ejecución exitosa de esta estructura o puedo manipular los procesos
a mi gusto, por ejemplo utilizando otro tipo de estructuras, o más de una estructura?

**Comment by Geeermy** [comment]
¡Hola!

La cola tiene como único objetivo, en este caso, que aglomeren en una única estructura un conjunto de procesos.

* ¿Es necesario que opere exactamente como una cola? **No, puede hacer cosas distintas.**
* ¿Es necesario tener una única cola? **No, pueden tener varias.**

Lo ideal es que uses dicha estructura, pero no nos importa mucho **cómo** la utilices. Está pensada más bien para que puedan modelar mejor el problema.

¡Espero resolver tu duda! :-)

**Comment by B-Dominguez** [comment]
Hola, es necesario implementar la estructura (creando nodos y asociandolos, etc) o puede usarse un array de procesos y en base a este crear funciones que permitan ordenar?

> struct queue{
> 	Process* arr = malloc(init_capacity * sizeof(Process));
> 	...
> }

**Comment by Geeermy** [comment]
Siguiendo mi comentario anterior, no, no es necesario. Puedes hacer lo que describes. :^)

**Comment by B-Dominguez** [comment]
Gracias. Ampliando la duda, es permitido usar código disponible en internet para implementar un vector (cola) y sus funciones?

**Comment by Geeermy** [comment]
@B-Dominguez Lo conversamos con el equipo docente y lo permitiremos, siempre que sea de una fuente en C y que esté correctamente citada.

**Comment by jmwielandt** [comment]
~~¿Necesariamente se tiene que llamar `Queue`?
En mi caso es una lista ligada, se me hace raro llamarla `Queue`, pensando en que sí tengo una `Queue` pero para otra cosa, no para guardar los procesos.~~

**EDIT:** Olvídenlo, soy tontito a veces 🤦‍♂️

**Comment by Geeermy** [comment]
Ojo con el vocabulario. 😁
