### ISSUE TITLE
leyendo el test

### ISSUE THREAD

**Issue by Dunkan1** [IIC2333/foro-2019-1#70]
Hola, no entiendo porque ocurre lo siguiente.
uso lo siguiente para leer cada palabra del archivo
```
while (fscanf(fptr, "%s", almacen) != EOF){}
```
cuando lo utilizo en threads funciona bien, pero cuando lo hago con forks,
lo que ocurre es que deja de reconocer el final del archivo y entra en un loop

**Comment by IchottMano** [comment]
Hola!

[Esta pregunta](https://stackoverflow.com/questions/878494/multiple-child-process-reading-from-a-stream) de StackOverflow puede serte útil para lo que estás intentando hacer, lamentablemente no puedo ayudarte mucho mas con la información que me estás dando 😅 

Saludos!

**Comment by Dunkan1** [comment]
gracias
