### ISSUE TITLE
Cantidad threads/forks

### ISSUE THREAD

**Issue by B-Dominguez** [IIC2333/foro-2019-1#71]
Hola, existe algún criterio para cuántos threads o forks deberían existir? Si son pocos threads (más de mil palabras por thread en map) se considerará malo?
Gracias!

**Comment by IchottMano** [comment]
Hola!

Como dijimos en la ayudantía/sala de ayuda, se recomienda **fuertemente** que en tu programa exista una variable global con la cantidad máxima de threads o procesos **concurrentes**.

Para la cantidad **total** de threads o procesos, esto queda a tu criterio, una cantidad baja de threads o procesos no se considerará malo, siempre y cuando estos sean múltiples (no puede ser sólo un thread/proceso para hacer map).

Saludos!
