### ISSUE TITLE
Pauta T2

### ISSUE THREAD

**Issue by Dunkan1** [IIC2333/foro-2019-1#72]
el manejo de Ctrl-C va en los 0.5 Pts. de "manejo de memoria" cierto?

**Comment by IchottMano** [comment]
Hola!

Por un lado, para el puntaje de manejo de memoria es necesario que se libere la memoria al cortar el programa con CTRL-C.

Por otro lado, influye en la comunicación de procesos, ya que se manejan señales (0,5 pts).

Saludos!

**Comment by Dunkan1** [comment]
ya veo, gracias
