### ISSUE TITLE
Ayudantía P1 - 01/05

### ISSUE THREAD

**Issue by Geeermy** [IIC2333/foro-2019-1#75]
¿Les gustaría que solo veamos el proyecto a fondo? ¿O lo acortamos para repasar paginación -tema importante en el Midterm-?

**Comment by diflores** [comment]
¡Repasemos paginación también! 📄

**Comment by jpjoublan** [comment]
Paginación también

**Comment by nfbalbontin** [comment]
Repaso!

**Comment by fprebolledo** [comment]
Paginación!

**Comment by fnquinteros** [comment]
Repaso porfa!

**Comment by pnheinsohn** [comment]
+1 al repaso!

**Comment by beayancan** [comment]
Apoyo el repaso

**Comment by Geeermy** [comment]
Solo para estar seguro: ¿están claros que el repaso será solo de paginación, cierto? 😅
