### ISSUE TITLE
Duda Tabla de Páginas AC05

### ISSUE THREAD

**Issue by ariel-m-s** [IIC2333/foro-2019-1#76]
Hola!

Tengo una duda acerca de la pregunta de tabla de páginas actividad 5 (direccionamiento y memoria virtual > paginación).

En el segundo ítem, donde preguntan acerca del tamaño que tendría la tabla de páginas del sistema descrito, ¿se pueden usar fracciones de _bytes_ o hay que asumir que la memoria siempre trabajará con bloques de a un _byte_?

Saludos,
Ariel

**Comment by cruz** [comment]
Hola Ariel,
El tamaño de la tabla de páginas se obtiene en Byte. Está pensado para que el resultado sea un valor entero (este es un gran _hint_) :)

Para esto considera la "altura" de la tabla de páginas, o sea, la cantidad de entradas (PTEs) que debe tener la tabla de página, que es exactamente la cantidad de páginas posibles en el sistema. En este caso hay 11 bit para el número de página así que hay que calcular cuantas combinaciones posibles podemos obtener con esos 11 bit.

Para conocer el "ancho" de la tabla de páginas debemos considerar los bits que se necesita para almacenar el número de frame (lo sacamos de los bit de la  dirección física, menos los del offset), y agregándole un bit más para la metadata, de acuerdo a lo que dice la pregunta.

Ese producto te entrega la cantidad de bit. Para obtener los Byte, divides por 2^3. Y eso debe dar un número entero. Avisa por aquí si llegas a la respuesta.

Saludos,

**Comment by ariel-m-s** [comment]
¡Muchas gracias @cruz! Llegué a la respuesta :)
