### ISSUE TITLE
Duda enunciado AC05 - Algoritmos de reemplazo - Algoritmos de aproximación a LRU

### ISSUE THREAD

**Issue by malopez16** [IIC2333/foro-2019-1#77]
Hola, en la pregunta que menciono en el título, me queda una duda con respecto a una alternativa: 

> El algoritmo del reloj elige siempre una página que tenga reference bit en 0 .

No me queda claro si se está refiriendo a elegir para removerla directamente o para hacer el cambio del reference bit. Sólo dice "elegir" pero no para qué, y eso me confunde un poco.

Muchas gracias!

Saludos,
Mauricio.

**Comment by cruz** [comment]
Hola Mauricio,
Buena pregunta. Ese _elegir_ se refiere a _elegirla para ser reemplazada_. El hecho de cambiarle el _reference bit_ no es técnicamente una "elección", sino que solamente pasa por ahí.

Voy a poner a aclaración en la pregunta misma.

Saludos y ánimo,

**Comment by malopez16** [comment]
Gracias por la respuesta! Ahora me quedó claro :)
