### ISSUE TITLE
AC04 - ¿Quién incrementa full?

### ISSUE THREAD

**Issue by ranieto** [IIC2333/foro-2019-1#79]
No sé si hay un error en la AC04 o si estoy entendiendo todo mal.
En la penúltima sección ("Semaforos y Variables de Condición"), la tercera pregunta ("Bounded Buffer con Semáforos") considera como correcta la alternativa "El semáforo `full` es incrementado solo por los consumidores". Pero lo que entiendo del [código](http://iic2333.ing.puc.cl/slides/1-proc.html#/sem-bounded-buffer) es todo lo contrario, porque veo que el productor es el que hace `full.V()`. ¿Es un error o estoy entendiendo algo mal?

**Comment by Geeermy** [comment]
¡Hola!

Sí, es un error. Debería decir "El semáforo `full` es incrementado solo por los productores".

No lo puedo modificar de inmediato, pero considera que ese es el arreglo, tu interpretación del código es correcta.

¡Éxito!

**Comment by cruz** [comment]
Hola.
Gracias por el aviso. Tienen toda la razón. Había varias maneras de corregirla, pero opté por usar el cambio propuesto por @Geeermy. La corregí y actualicé la cantidad de oportunidades para dejarla en seis (no encontré la manera de resetear los intentos de todos).
