### ISSUE TITLE
Cantidad Total de Tiempo

### ISSUE THREAD

**Issue by pnheinsohn** [IIC2333/foro-2019-1#8]
Hola! estoy tratando de calcular las estadísticas, pero en el "output" que nos entregan no sale cuantas iteraciones se realizan en total en el "test1.txt", por lo que me tiene un poco complicado ya que no sé si estoy simulando bien la tarea.

**Comment by Geeermy** [comment]
¡Hola!

¿Para qué necesitas saber eso? Puedes asumir el tiempo de término como la iteración en la que el último proceso en ejecución pasa a estado `FINISHED`. Después de eso no nos interesa mucho lo que pase.

Por esa razón no es necesario tenerlo indicado en los _tests_... ¿te hace sentido? ¡Avísame si quedas con dudas!

**Comment by pnheinsohn** [comment]
Perfect!
