### ISSUE TITLE
crFILE* cr_open

### ISSUE THREAD

**Issue by movaldivia** [IIC2333/foro-2019-1#82]
Esta función para programarla podemos usar FILE por dentro o hay otra manera?

**Comment by Geeermy** [comment]
¡Hola! (otra vez)

En teoría, no tienen la restricción del uso de la clase `FILE` (si no, no tendrían archivos). No obstante, es importante destacar que en este método la ruta `path` es del **disco binario**, no de tu máquina local (por eso en el método `cr_open` en particular `FILE` no te servirá mucho). Los métodos `load` y `unload` **sí trabajan** con rutas de la máquina local, por lo que en estos querrías usar esa clase para leer/escribir archivos directamente. Sugiero que leas bien todas las descripciones para notar estas particularidades.

¡Éxito! (otra vez) :)

**Comment by Geeermy** [comment]
**IMPORTANTE:** Acabo de notar que, como tienen que estar leyendo constantemente el disco binario, este debe ser instanciado con la `struct FILE`. Por lo tanto sí, pueden (y **deben**) usar `FILE`. Creo que por eso surgía tu pregunta, así que lo siento por irme por las ramas. :-(

¡Nos vemos!

**Comment by movaldivia** [comment]
@Geeermy Aaaaa ya decia yo jajajajaja. Gracias de nuevo!
