### ISSUE TITLE
Error al leer disco

### ISSUE THREAD

**Issue by jorgeriesco** [IIC2333/foro-2019-1#83]
Hola, 

Al abrir el archivo .bin e intentar leer dentro de un directorio cada 32 bytes, solo para confirmar que la lectura es efectiva, parece funcionar y valgrind no tira errores , pero luego aparece lo siguiente en consola:

*** stack smashing detected ***: <unknown> terminated
Abortado (`core' generado)

Alguna idea de que podriamos estar haciendo mal?

Gracias.

**Comment by IchottMano** [comment]
Hola!

Ese error suele ocurrir cuando intentas escribir en una variable del stack algo que es mas grande que el espacio que tienes (como si hicieras malloc(sizeof(char)*12) para despues pegarle un string de largo 13, solo que en vez de que esto ocurra en el heap (donde esta la memoria asignada dinamicamente) esto ocurren en el stack.

Intenta revisar que los buffers que usas sean lo suficientemente grandes para guardar tus datos.

Avisame si tienes mas dudas.
Saludos!

**Comment by Geeermy** [comment]
@jorgeriesco Por favor, se agradece si puedes actualizar el estado de esta _issue_: ¿resolviste tu problema?

**Comment by jorgeriesco** [comment]
Disculpen! SI esta resuleta. Muchas gracias!
