### ISSUE TITLE
Sobre bitmap

### ISSUE THREAD

**Issue by malopez16** [IIC2333/foro-2019-1#84]
Hola,

¿El disco del archivo simdiskfilled tiene el bitmap poblado?

Hasta donde entendí leyendo el enunciado, está bien si los primeros bytes del primer bloque de bitmap están poblados. Mi problema es que al leer el disco que está lleno (simdiskfilled), sólo me tira un número distinto a 0 en los primeros bytes del primer bloque, pero en ningún otro. Teniendo varios archivos, yo asumiría que deberían estar reflejados en el bitmap. 

Después de haber estado harto rato, quería comprobar que efectivamente si estaba el bitmap poblado y por algún motivo no me está funcionando. Me parece raro que me aparezcan sólo los bits de los primeros bloques y de los otros no.

Por otro lado, puedo no estar entendiendo esto bien, por lo que si es el caso, preferí mejor preguntar por acá.

Gracias,
Saludos :)

**Comment by IchottMano** [comment]
Hola!

Seguro que estas usando el *simdiskfilled.bin* y no el *simdiskformat.bin*?

Viendo por medio de Sublime Text el inicio del primer bloque de bitmap, puedo ver varios bits que son distintos de cero, por lo que el bitmap del disco si esta poblado.

![bitmap](https://user-images.githubusercontent.com/26393051/57586125-203db000-74bf-11e9-822f-516fdf720106.png)

Saludos!

**Comment by malopez16** [comment]
Sí, estoy usando el que está en el zip de la ayudantía. Debo estar haciéndola mal :( .
gracias :)

Edit: Será que ese disco de la ayudantía no tiene el bitmap creado?

**Comment by Geeermy** [comment]
:( El `simdiskfilled.bin` subido en el .zip de la ayudantía **es un ejemplo de juguete.** Lo utilizamos en esta el viernes para poder ver rápidamente cómo hacer una versión preliminar del método `cr_ls` y que aprendieran a ver cómo hacer la lectura de archivos binarios.

El `simdiskfilled.bin` real se descarga **según las instrucciones del enunciado** (haciendo uso de `scp` desde la ruta indicada).

Actualizándolo con el disco correcto deberías ver bien los bloques de _bitmap_. Confírmanos de todas maneras. :)

PD: No es nuestra culpa, sino que de tus plenarias. 💔

**Comment by malopez16** [comment]
@Geeermy Oh baia! No hay problema! Lo estoy descargando ahora mismo. 
Gracias :)

PD: Estoy de acuerdo con tu PD. Yo preferiría ir a las ayudantías xd

**Comment by malopez16** [comment]
Buena! Ahora sí. Gracias a ambos. Disculpen la molestia jaja

**Comment by vamussuto** [comment]
Hola, aprovecho esta issue para preguntar si nos pueden dar los valores correctos de bloques ocupados y libres en el disco del servidor (simdiskfilled.bin) para poder testear nuestro resultado.

Gracias!

**Comment by IchottMano** [comment]
@vamussuto Hola!
En el disco hay 8813 bloques ocupados y 56723 bloques libres.
Saludos!

**Comment by vamussuto** [comment]
Gracias!

**Comment by naoliden** [comment]
@IchottMano Hola, 
El bitmap del disco debe verse como el del ejemplo de más arriba? 
No vale que sea solo una serie de 1 y 0? y qué es lo que imprimiste? pq esta en hexa.

saludos!

**Comment by Geeermy** [comment]
@norman123123 Richi solo subió un pantallazo para mostrar cómo se ve un archivo binario en el editor de texto Sublime Text para evidenciar que, efectivamente, el disco tiene escrituras (si no las tuviera, solo tendría ceros). Lo único que pasa en el editor es que en vez de mostrarte los bits (1's o 0's) te muestra en hexadecimal aglomerados de 4 bits (con 4 bits puedes expresar un dígito en hexadecimal, por eso lo hacen así).

Lo que dices tú está bien y no solo es válido, es **justamente** lo que les pedimos en el enunciado.

¡Que estés bien!

**Comment by sjmunoz** [comment]
> @vamussuto Hola!
> En el disco hay 8813 bloques ocupados y 56723 bloques libres.
> Saludos!

Podrian subir estos mismo numeros de los nuevos discos?

Gracias!

**Comment by Geeermy** [comment]
@santi95 Eso está en el nuevo archivo `bitmap.txt` que les dejamos subido en el servidor y que pueden descargar según las instrucciones del último aviso enviado.

¡Éxito!
