### ISSUE TITLE
asignación indexada de dos niveles

### ISSUE THREAD

**Issue by movaldivia** [IIC2333/foro-2019-1#85]
En el enunciado sale "El sistema almacena archivos en bloques mediante asignación indexada de dos niveles" que significa eso?

**Comment by Geeermy** [comment]
¡Hola!

Significa que usa punteros directos a bloques de datos (primer nivel) y punteros a bloques direccionamiento indirecto (segundo nivel). Esta diapositiva hace mención de esto: http://iic2333.ing.puc.cl/slides/5-disk.html#/6/10

¡Éxito!

**Comment by movaldivia** [comment]
Gracias @Geeermy !!
