### ISSUE TITLE
Path Funciones

### ISSUE THREAD

**Issue by TomasFuentes** [IIC2333/foro-2019-1#86]
Hola!!. 
Junto a mi grupo estamos un poco confundidos en cómo vendría dada la path que reciben los métodos cr_exist, cr_ls, etc. Que parámetros hay que entregarle a esta? una dirección absoluta?.

Saludos

**Comment by Geeermy** [comment]
¡Hola!

De partida, no hay métodos de navegación en el sistema de archivos (como por ejemplo, `cd`), por lo que siempre trabajaremos con rutas absolutas.

Por otra parte, la nomenclatura esperada en general es esta: si es el nombre directo de un archivo o directorio (por ejemplo, `archivo.txt` o `carpeta`), simplemente es un archivo de la carpeta `root` (bloque cero). En otro caso, será un archivo ubicado en un subdirectorio y el nombre en la ruta partirá con el nombre de la primera subcarpeta, por ejemplo: `carpeta1/carpeta2/archivo.txt`.

Si quieren hacer algo más elaborado (por ejemplo, permitir rutas del tipo `./archivo.txt` o `./carpeta/archivo.txt`) o bien algo distinto de lo que detallé antes (por eso puse "nomenclatura esperada"), pueden hacerlo siempre que lo especifiquen en el README. Hay flexibilidad en este caso dado que no se estableció de forma explícita en el enunciado.

¡Espero haber aclarado el panorama! :)

**Comment by acrojas2** [comment]
Hola, 
Cómo seria el path para el ls del directorio root?
Saludos!

**Comment by Geeermy** [comment]
¡Hola!

Como ustedes prefieran, siempre que tenga sentido. Por ejemplo, `"."`, `"/"` y `"./"` son rutas válidas para  `root` (obviamente, no es necesario que consideren todos esos casos, hagan el o los que prefieran).

¡Éxito!
