### ISSUE TITLE
Duda con cr_exists

### ISSUE THREAD

**Issue by jpjoublan** [IIC2333/foro-2019-1#88]
Hola!

Nos surgió una duda con la función `int cr_exists(char * path)`, que es para verificar si un archivo o carpeta existe en la ruta. Esto se refiere a que tenemos que verificar que el `path` ingresado sea válido/exista? O falta un argumento en la función que indique el nombre del archivo que tenemos que buscar en la ruta?

Gracias!

**Comment by Geeermy** [comment]
¡Hola!

La ruta (`path`) **incluye** el nombre del archivo. Si quiero ver que existe el archivo `f.txt` en la carpeta `carpeta`, utilizo: `cr_exists("carpeta/f.txt")`. Si quisiera ver la existencia de la `carpeta` en el directorio raíz, entonces utilizo: `cr_exists("carpeta")`. ¿Se entiende?

¡Éxito!

**Comment by Geeermy** [comment]
Más información en: #86

**Comment by jpjoublan** [comment]
Sí se entendió, gracias!
