### ISSUE TITLE
Dudas cr_mkdir y cr_open

### ISSUE THREAD

**Issue by vamussuto** [IIC2333/foro-2019-1#89]
Hola, con mi grupo tenemos algunas dudas de estas dos funciones.

1. En cr_open ¿qué pasa si mode es distinto a 'r'?, ya que en el enunciado solo se explica que debe hacer la función cuando mode es 'r'.

2. En cr_mkdir, ¿solo se pueden crear nuevos directorios dentro del directorio raíz o podría hacerlo en otros?. Con lo último me refiero a hacer cr_mkdir("/folder1/folder2/new_folder"), creando un nuevo directorio dentro de folder2.

Gracias!

**Comment by Geeermy** [comment]
¡Hola!

1) Ya, esa fue mala nuestra. Estaba en el latex del enunciado, pero quedó comentado. 😓 Cito lo original: `"Si mode es 'w', se verifica que el archivo no exista en la ruta especificada y se retorna un nuevo crFILE* que lo representa."` La idea es básicamente que se cree un nuevo archivo, el que después se creará como una nueva entrada del directorio en la ruta indicada y se empezará a escribir con el método `cr_write` (esto implicará, obviamente, el uso de un nuevo bloque de archivo y el uso de bloques de datos nuevos). Obviamente, el manejo de posibles errores por mal uso (por ejemplo, escribir en modo lectura) lo tienen que ver ustedes y es parte del bonus. Si tienes más dudas de lo que se espera del método, sigue consultando por aquí.

2) Sí, deben poder hacerlo en la raíz o en un subdirectorio. La nomenclatura que utilizas para ejemplificar sería un ejemplo válido de eso.

¡Que estés bien! :)

**Comment by vamussuto** [comment]
Gracias!
