### ISSUE TITLE
entrada de proceso

### ISSUE THREAD

**Issue by fprebolledo** [IIC2333/foro-2019-1#9]
Si tengo un proceso que entra en tiempo 0, este entra a la cola?  o pasa a estar running ? gracias.

**Comment by IchottMano** [comment]
Hola!

Si un proceso entra en tiempo 0, efectivamente pasará inmediatamente a estado RUNNING.

Saludos!

**Comment by Geeermy** [comment]
**Como comentario adicional:** da lo mismo si lo modelas primero entrando a la cola y posteriormente pasando a `RUNNING` en la CPU, o bien pasándolo directamente a `RUNNING`, para que no te compliques con tu implementación. Lo que **sí importa** es que en t=0 el proceso alcance a ejecutar una unidad de tiempo, ya que la CPU estará desocupada y no puede desperdiciar esa iteración. La forma en la que lo hagas por detrás no nos importa mucho. 😁
