### ISSUE TITLE
multiples scripts main.c

### ISSUE THREAD

**Issue by acrojas2** [IIC2333/foro-2019-1#90]
Hola: 
En alguna parte del enunciado dice que debemos implementar _uno o mas_ archivos main.c para mostrar el uso de las funcionalidades implementadas. De lo anterior dos dudas:

1. ¿Es necesario hacer más de un scripst main o queda a criterio del grupo? 
2. ¿Cómo se hace más de un script main.c? Creo que en algún momento de alguna clase escuché que el profesor dijo que la funcion main que se ejecuta es unica.  Si hiciera mas de un script main, lo haría con el objetivo de tener un control flujo (llamar a otra/s funciones) distinto al de los otros scripts main entonces no entiento cómo se hace más de un script main para cambiar el flujo de la funcion main.

Saludos.

**Comment by Geeermy** [comment]
¡Hola Ale!

1. Queda al criterio del grupo. Recuerda que esto no es para la entrega formal (en el plazo establecido a través de su repositorio), sino que es para que ilustren el funcionamiento de su API en la corrección presencial. Pueden mostrar ciertas funcionalidades en cada `main`, o bien mostrar todo en uno solo.

2. Básicamente, defines otro _script_ `main.c` (por ejemplo, `main2.c`) donde hagan otros cambios sobre el disco y después los compilas con algo _similar_ a esto en el `Makefile`:

```
all: crfs1 crfs2

crfs1: main.c cr_API.c
        gcc -o crfs1 main.c cr_API.c

crfs2: main2.c cr_API.c
        gcc -o crfs2 main2.c cr_API.c
```

Si te fijas, simplemente compilo dos programas distintos que hacen uso de la misma librería. Eso es lo que esperamos si es que deciden implementar más de un _script_ `main.c`. Da lo mismo que ninguno se llame `crfs` igual que en el enunciado, dado que en este proyecto nos interesa más la librería y su funcionamiento correcto que el programa compilado en sí.

¡Espero que se entienda! :)

**Comment by Geeermy** [comment]
Por favor, confírmame si solucionaste tu duda.

**Comment by acrojas2** [comment]
Hola:
Si, clarisimo. No sabía que se podían hacer esas cosas :hushed:. 
Gracias!
