### ISSUE TITLE
"simdiskfilled.bin" en Servidor 

### ISSUE THREAD

**Issue by nfbalbontin** [IIC2333/foro-2019-1#91]
Hola! Qué tal? 
No logro encontrar la carpeta en a que está el simdiskfilled.bin en el servidor, agradecería indicaciones :). 
Gracias

**Comment by IchottMano** [comment]
Hola!
El disco se encuentra en ```home/iic2333/P1/```.
Si quieres copiarlo a tu computador puedes usar
```bash
scp <usuario>@iic2333.ing.puc.cl:/home/iic2333/P1/simdiskfilled.bin .
```
Saludos!

**Comment by nfbalbontin** [comment]
Gracias!
