### ISSUE TITLE
Política de asignación de bloque

### ISSUE THREAD

**Issue by movaldivia** [IIC2333/foro-2019-1#92]
Hola leyendo el enunciado no encontré que se hablara de alguna política de asignación de bloques. Elegimos nosotros la política, leí mal o simplemente elegimos el bloque más cercano?

**Comment by Geeermy** [comment]
¡Hola!

Eso es intencional y pensado en que ustedes lo decidan. Escoger el (o los) primeros bloques que encuentres libres es más que razonable.

¡Éxito! :)

**Comment by movaldivia** [comment]
@Geeermy gracias !!!
