### ISSUE TITLE
cr_read última posición

### ISSUE THREAD

**Issue by movaldivia** [IIC2333/foro-2019-1#94]
![image](https://user-images.githubusercontent.com/24725124/57818531-4333c280-7752-11e9-944b-0d7fdc5f7507.png)

La última posición leida está dada por el buffer (efectivos) o los nbytes?

**Comment by Geeermy** [comment]
Está dada por _buffer_. Imagínate que _buffer_ es un puntero de 4KB y quieres llenarlo con 2 bloques de 2KB. Entonces, el flujo será _algo así_:

```
cr_read(f, buffer, 2048); // Lo lleno con 2KB.
// Con el método anterior llené el contenido desde la posición 0 a la 2047. 
// Ahora, paso el puntero de la posición 2048 para que parta desde ahí.
cr_read(f,&buffer[2048],2048); 
```

¡Espero que se entienda!

**Comment by movaldivia** [comment]
@Geeermy gracias, se entiende perfecto !!
