### ISSUE TITLE
tests t2 

### ISSUE THREAD

**Issue by fprebolledo** [IIC2333/foro-2019-1#95]
Hola! me gustaría saber si podrían subir los tests con que revisaron la T2 ya que yo hice varios, y me funcionaba, y en los comentarios dice que mi programa se cae, me gustaría poder ver si efectivamente es así o porqué para saber si recorregir o no.
Gracias.

**Comment by IchottMano** [comment]
Hola!
Como se dijo en la issue anunciando las notas de la tarea, para testear se usó el segundo test entregado anteriormente, que se encuentra en la página del curso, en específico se llama "text2.txt".
Saludos!
