### ISSUE TITLE
Duda cr_open

### ISSUE THREAD

**Issue by Dunkan1** [IIC2333/foro-2019-1#96]
Hola, tengo una duda con cr_open y lo que llega al final a cr_write, mi duda es si cuando llamo a cr_open con mode 'w' este, (siempre que no exista el nombre del archivo en la ruta) crea el bloque indice para el archivo, entonces en cr_write ya esta creado ese bloque indice o debo crearlo en cr_write?

Gracias.

**Comment by Geeermy** [comment]
¡Hola!

Dado que no está explicitado, no podemos imponer una forma. No obstante lo anterior, me parece más correcto que se cree una entrada en el directorio y el bloque índice correspondiente al hacer `cr_open` (imagínate que no se puede crear el archivo porque ya no hay bloques libres para poder crear un bloque índice... mejor controlarlo al momento de intentar crear el archivo).

¡Espero que se entienda!

**Comment by Dunkan1** [comment]
Gracias Germy
