### ISSUE TITLE
cr_write

### ISSUE THREAD

**Issue by Dunkan1** [IIC2333/foro-2019-1#98]
Hola queria quedar claro, estan bien estos posibles llamados a cr_write? 
```
crFILE* file_desc = cr_open("/path/a/escrivir.p", 'w');

void* buffer = "hola esta es una prueba";

cr_write(file_desc, buffer, 23);
```
```
crFILE* file_desc = cr_open("/path/a/escrivir.p", 'w');

void* buffer = fopen("~/Music/musica.mp3", "rb" );

cr_write(file_desc, buffer, 1048576);
```
Gracias

**Comment by Geeermy** [comment]
¡Hola!

Voy a separar tu código: el primero donde escribes un string (1) y el segundo donde escribes un archivo de audio (2).

1) Sí, pero me parece que son 24 bytes y no 23, dado que te falta incluir el término de string.

2) Aquí ten cuidado. Lo que debieses hacer es leer el contenido de `musica.mp3` (con `fread`) en el buffer y no que el buffer sea el puntero de tu archivo. En el primer ejercicio de la última ayudantía que hice hay un ejemplo de eso, donde incluso obtienes directamente el número de bytes del archivo sin tener que _hardcodearlo_ en código.

**Otra cosa importante:** Como no lo especificamos, tú decides cómo manejar la sobreescritura en archivos ya existentes. Puedes asumir que no va a pasar (lo que es válido) o bien: (i) liberar todos los bloques de datos utilizados y empezar una escritura desde cero; o (ii) reescribir los datos en los bloques ya asignados y ver qué hacer con los bloques que sobren o que falten. Estos dos últimos manejos, al no estar especificados, pueden ser considerados bonus en tu implementación. No obstante, no es necesario que te enfoques en ellos preliminarmente (recomiendo priorizar todas las funcionalidades mínimas primero).

¡Que estés bien y éxito!
