### ISSUE TITLE
archivo contenido bitmap

### ISSUE THREAD

**Issue by acrojas2** [IIC2333/foro-2019-1#99]
Hola,
En el enunciado, en la parte donde explican lo que hace la funcion bitmap, sale que en 1 línea se imprimen los bits de esos bloques. Nosé si está bien pensando en que son 65 mil y algo bloques.

¿se pueden imprimir de a 1Byte?
¿pueden subir el archivo con el resultado correcto para comparar que estan identificando bien  los bits?
Saludos!

**Comment by Geeermy** [comment]
¡Hola!

Sí, está bien. Por eso cobra importancia el hecho de hacerlo por `stderr`, de forma que lo puedas escribir en un archivo separado (ver #93). La idea es imprimirlo en bits, no en Byte. Lo siento. :( 

Con respecto al archivo con el resultado correcto: quedo de confirmar si podemos (más por un tema de tiempo que otra cosa). Espero tener noticias pronto.

¡Que estés bien!

**Comment by acrojas2** [comment]
Hola: 
Creo que no lo dije bien, cuando me refería a imprimirlo de a 1Byte, era 1Byte en bits, de la siguiente forma:
<img width="288" alt="Captura de pantalla 2019-05-16 a la(s) 21 52 16" src="https://user-images.githubusercontent.com/26121354/57898229-249efb80-7826-11e9-835b-24101eb62b61.png">
Saludos!

**Comment by Geeermy** [comment]
Aaaaaaaaaaah. Está perfecto, ningún problema.

¡Buen trabajo! 😄

**Comment by Geeermy** [comment]
[bitmap.txt](https://github.com/IIC2333/foro-2019-1/files/3189713/bitmap.txt)

Ahí tienes. Parece que te da correcto. :)

**Comment by Geeermy** [comment]
Revisé y al ojo parece que imprimes al revés el Byte. :eyes:

Fíjate que el primer Byte te deberían dar los primeros 5 bits iguales a 1. Si lo estás haciendo al revés, probablemente te aparecerán los 5 últimos iguales a 1. Me confirmas cualquier cosa.

**Comment by acrojas2** [comment]
Hola!
Estaba escribiendo al reves los bytes, pero ya lo solucioné. 
Gracias!
Saludos!
